#ifdef TARGET_ARM
typedef void (*on_sys_link_return_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_timerfd_create_enter_t)(CPUState* env,target_ulong pc,int32_t clockid,int32_t flags);
typedef void (*on_sys_pivot_root_enter_t)(CPUState* env,target_ulong pc,target_ulong new_root,target_ulong put_old);
typedef void (*on_sys_listxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_move_pages_return_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t nr_pages,target_ulong pages,target_ulong nodes,target_ulong status,int32_t flags);
typedef void (*on_sys_inotify_init_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fallocate_return_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t mode,uint64_t offset,uint64_t len);
typedef void (*on_execve_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong argv,target_ulong envp);
typedef void (*on_ARM_breakpoint_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_rt_sigaction_return_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact,uint32_t sigsetsize);
typedef void (*on_sys_inotify_init1_enter_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_capset_return_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong data_arg);
typedef void (*on_sys_sync_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_syslog_enter_t)(CPUState* env,target_ulong pc,int32_t type,target_ulong buf,int32_t len);
typedef void (*on_sys_getegid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setuid16_enter_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_mount_enter_t)(CPUState* env,target_ulong pc,target_ulong dev_name,target_ulong dir_name,target_ulong type,uint32_t flags,target_ulong data_arg);
typedef void (*on_sys_getgroups_enter_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_getrusage_return_t)(CPUState* env,target_ulong pc,int32_t who,target_ulong ru);
typedef void (*on_sys_newlstat_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_poll_return_t)(CPUState* env,target_ulong pc,target_ulong ufds,uint32_t nfds,int32_t timeout);
typedef void (*on_sys_setregid_return_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_sethostname_enter_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_rt_sigqueueinfo_return_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig,target_ulong uinfo);
typedef void (*on_sys_getcwd_enter_t)(CPUState* env,target_ulong pc,target_ulong buf,uint32_t size);
typedef void (*on_sys_close_return_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_setresgid16_enter_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_setresuid16_return_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_sigprocmask_return_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset);
typedef void (*on_sys_chroot_return_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_getgid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_mq_getsetattr_enter_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong mqstat,target_ulong omqstat);
typedef void (*on_sys_lookup_dcookie_enter_t)(CPUState* env,target_ulong pc,uint64_t cookie64,target_ulong buf,uint32_t len);
typedef void (*on_sys_fcntl_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_setresgid_enter_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_mq_unlink_enter_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_gettimeofday_enter_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_fchdir_return_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_flistxattr_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong list,uint32_t size);
typedef void (*on_sys_sched_setparam_return_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_rt_sigsuspend_enter_t)(CPUState* env,target_ulong pc,target_ulong unewset,uint32_t sigsetsize);
typedef void (*on_sys_munlock_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_setfsuid16_enter_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_fdatasync_return_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_reboot_enter_t)(CPUState* env,target_ulong pc,int32_t magic1,int32_t magic2,uint32_t cmd,target_ulong arg);
typedef void (*on_sys_io_destroy_enter_t)(CPUState* env,target_ulong pc,uint32_t ctx);
typedef void (*on_sys_sched_yield_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_mknod_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_delete_module_return_t)(CPUState* env,target_ulong pc,target_ulong name_user,uint32_t flags);
typedef void (*on_sys_sched_rr_get_interval_return_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong interval);
typedef void (*on_sys_sendmsg_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_ioctl_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_symlinkat_return_t)(CPUState* env,target_ulong pc,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_ARM_set_tls_enter_t)(CPUState* env,target_ulong pc,uint32_t arg);
typedef void (*on_sys_timer_settime_enter_t)(CPUState* env,target_ulong pc,uint32_t timer_id,int32_t flags,target_ulong new_setting,target_ulong old_setting);
typedef void (*on_sys_mknodat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_stat64_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_pwrite64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_setpriority_return_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t niceval);
typedef void (*on_sys_clock_nanosleep_return_t)(CPUState* env,target_ulong pc,uint32_t which_clock,int32_t flags,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_tgkill_return_t)(CPUState* env,target_ulong pc,int32_t tgid,int32_t pid,int32_t sig);
typedef void (*on_sys_getxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_getcpu_enter_t)(CPUState* env,target_ulong pc,target_ulong cpu,target_ulong node,target_ulong cache);
typedef void (*on_sys_setresgid16_return_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_mq_open_enter_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t oflag,uint32_t mode,target_ulong attr);
typedef void (*on_sys_lgetxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_sendmsg_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_personality_return_t)(CPUState* env,target_ulong pc,int32_t personality);
typedef void (*on_sys_sigpending_enter_t)(CPUState* env,target_ulong pc,target_ulong set);
typedef void (*on_sys_set_robust_list_enter_t)(CPUState* env,target_ulong pc,target_ulong head,uint32_t len);
typedef void (*on_sys_exit_return_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_timerfd_gettime_enter_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong otmr);
typedef void (*on_sys_ioprio_get_enter_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_semctl_return_t)(CPUState* env,target_ulong pc,int32_t semid,int32_t semnum,int32_t cmd,uint32_t arg);
typedef void (*on_sys_sched_rr_get_interval_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong interval);
typedef void (*on_sys_pause_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_recvfrom_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,target_ulong arg5);
typedef void (*on_sys_sched_getaffinity_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_add_key_enter_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _payload,uint32_t plen,uint32_t destringid);
typedef void (*on_sys_timerfd_create_return_t)(CPUState* env,target_ulong pc,int32_t clockid,int32_t flags);
typedef void (*on_sys_chroot_enter_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_nice_enter_t)(CPUState* env,target_ulong pc,int32_t increment);
typedef void (*on_sys_getpgrp_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_rt_sigtimedwait_enter_t)(CPUState* env,target_ulong pc,target_ulong uthese,target_ulong uinfo,target_ulong uts,uint32_t sigsetsize);
typedef void (*on_sys_io_setup_enter_t)(CPUState* env,target_ulong pc,uint32_t nr_reqs,target_ulong ctx);
typedef void (*on_sys_shmat_enter_t)(CPUState* env,target_ulong pc,int32_t shmid,target_ulong shmaddr,int32_t shmflg);
typedef void (*on_sys_socket_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2);
typedef void (*on_sys_getresuid_return_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_faccessat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode);
typedef void (*on_do_mmap2_return_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len,uint32_t prot,uint32_t flags,uint32_t fd,uint32_t pgoff);
typedef void (*on_sys_sysfs_enter_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg1,uint32_t arg2);
typedef void (*on_sys_truncate64_return_t)(CPUState* env,target_ulong pc,target_ulong path,uint64_t length);
typedef void (*on_sys_setpgid_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t pgid);
typedef void (*on_sys_setresuid16_enter_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_access_return_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode);
typedef void (*on_sys_mlock_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_ftruncate_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t length);
typedef void (*on_sys_mlock_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_shmget_enter_t)(CPUState* env,target_ulong pc,uint32_t key,uint32_t size,int32_t flag);
typedef void (*on_sys_geteuid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sigreturn_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_brk_return_t)(CPUState* env,target_ulong pc,uint32_t brk);
typedef void (*on_sys_fstatat64_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong statbuf,int32_t flag);
typedef void (*on_sys_lgetxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_getegid16_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_keyctl_enter_t)(CPUState* env,target_ulong pc,int32_t cmd,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_utimensat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes,int32_t flags);
typedef void (*on_sigreturn_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fchown_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_getpgid_return_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_rename_enter_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_fchmod_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t mode);
typedef void (*on_sys_get_robust_list_enter_t)(CPUState* env,target_ulong pc,int32_t pid,target_ulong head_ptr,target_ulong len_ptr);
typedef void (*on_sys_getrlimit_enter_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_setpgid_return_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t pgid);
typedef void (*on_sys_get_mempolicy_enter_t)(CPUState* env,target_ulong pc,target_ulong policy,target_ulong nmask,uint32_t maxnode,uint32_t addr,uint32_t flags);
typedef void (*on_sys_inotify_add_watch_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong path,uint32_t mask);
typedef void (*on_vfork_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_shmdt_return_t)(CPUState* env,target_ulong pc,target_ulong shmaddr);
typedef void (*on_sys_capset_enter_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong data_arg);
typedef void (*on_sys_shmctl_return_t)(CPUState* env,target_ulong pc,int32_t shmid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_fcntl64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_clock_settime_return_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_gettid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setuid_enter_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_set_tid_address_return_t)(CPUState* env,target_ulong pc,target_ulong tidptr);
typedef void (*on_sys_pciconfig_read_return_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_removexattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_setfsgid16_enter_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_kill_enter_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_ioctl_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_open_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_fchownat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t user,uint32_t group,int32_t flag);
typedef void (*on_sys_pread64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_sched_getparam_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_nanosleep_enter_t)(CPUState* env,target_ulong pc,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_getpgid_enter_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_umount_enter_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t flags);
typedef void (*on_sys_msgget_enter_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t msgflg);
typedef void (*on_sys_unlink_return_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_times_enter_t)(CPUState* env,target_ulong pc,target_ulong tbuf);
typedef void (*on_sys_sched_get_priority_min_enter_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_connect_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_accept_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_vhangup_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_chmod_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t mode);
typedef void (*on_all_sys_linux_arm_return_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_sys_setregid_enter_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_swapoff_enter_t)(CPUState* env,target_ulong pc,target_ulong specialfile);
typedef void (*on_sys_madvise_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t behavior);
typedef void (*on_sys_sched_getparam_return_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_setgroups16_return_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_fsync_enter_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_readlink_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_ustat_return_t)(CPUState* env,target_ulong pc,uint32_t dev,target_ulong ubuf);
typedef void (*on_sys_link_enter_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_sync_file_range2_return_t)(CPUState* env,target_ulong pc,int32_t fd,uint32_t flags,uint64_t offset,uint64_t nbytes);
typedef void (*on_ARM_breakpoint_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_pivot_root_return_t)(CPUState* env,target_ulong pc,target_ulong new_root,target_ulong put_old);
typedef void (*on_sys_fgetxattr_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_setdomainname_enter_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_recv_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_epoll_ctl_return_t)(CPUState* env,target_ulong pc,int32_t epfd,int32_t op,int32_t fd,target_ulong event);
typedef void (*on_sys_signalfd4_enter_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask,int32_t flags);
typedef void (*on_sys_set_mempolicy_return_t)(CPUState* env,target_ulong pc,int32_t mode,target_ulong nmask,uint32_t maxnode);
typedef void (*on_sys_mknod_return_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_sethostname_return_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_io_submit_enter_t)(CPUState* env,target_ulong pc,uint32_t arg0,int32_t arg1,target_ulong arg2);
typedef void (*on_sys_setfsgid16_return_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sigaction_enter_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact);
typedef void (*on_sys_getdents_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_lstat64_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_shmat_return_t)(CPUState* env,target_ulong pc,int32_t shmid,target_ulong shmaddr,int32_t shmflg);
typedef void (*on_sys_setsockopt_return_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,int32_t optlen);
typedef void (*on_sys_renameat_return_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_shutdown_return_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_getresuid_enter_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_request_key_return_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _callout_info,uint32_t destringid);
typedef void (*on_sys_setfsuid16_return_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_getresgid_return_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_clock_getres_return_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_getuid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_keyctl_return_t)(CPUState* env,target_ulong pc,int32_t cmd,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_writev_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_quotactl_return_t)(CPUState* env,target_ulong pc,uint32_t cmd,target_ulong special,uint32_t id,target_ulong addr);
typedef void (*on_do_sigaltstack_enter_t)(CPUState* env,target_ulong pc,target_ulong uss,target_ulong uoss);
typedef void (*on_sys_getppid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_semop_return_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops);
typedef void (*on_execve_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong argv,target_ulong envp);
typedef void (*on_sys_semtimedop_return_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops,target_ulong timeout);
typedef void (*on_sys_getdents64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_getsid_enter_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_ARM_cacheflush_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t end,uint32_t flags);
typedef void (*on_unknown_sys_linux_arm_enter_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_sys_openat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_statfs_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf);
typedef void (*on_sys_io_getevents_enter_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,int32_t min_nr,int32_t nr,target_ulong events,target_ulong timeout);
typedef void (*on_sys_timerfd_settime_enter_t)(CPUState* env,target_ulong pc,int32_t ufd,int32_t flags,target_ulong utmr,target_ulong otmr);
typedef void (*on_sys_getgid16_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_timer_create_return_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong timer_event_spec,target_ulong created_timer_id);
typedef void (*on_sys_restart_syscall_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fstat64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_munmap_enter_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len);
typedef void (*on_sys_splice_enter_t)(CPUState* env,target_ulong pc,int32_t fd_in,target_ulong off_in,int32_t fd_out,target_ulong off_out,uint32_t len,uint32_t flags);
typedef void (*on_sys_pipe_enter_t)(CPUState* env,target_ulong pc,target_ulong arg0);
typedef void (*on_sys_mq_getsetattr_return_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong mqstat,target_ulong omqstat);
typedef void (*on_sys_kexec_load_return_t)(CPUState* env,target_ulong pc,uint32_t entry,uint32_t nr_segments,target_ulong segments,uint32_t flags);
typedef void (*on_sys_getsockname_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_vmsplice_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong iov,uint32_t nr_segs,uint32_t flags);
typedef void (*on_rt_sigaction_enter_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact,uint32_t sigsetsize);
typedef void (*on_sys_newstat_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_lsetxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_timer_gettime_enter_t)(CPUState* env,target_ulong pc,uint32_t timer_id,target_ulong setting);
typedef void (*on_sys_symlink_enter_t)(CPUState* env,target_ulong pc,target_ulong old,target_ulong anew);
typedef void (*on_sys_getgroups16_enter_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_sigprocmask_enter_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset);
typedef void (*on_fork_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_umount_return_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t flags);
typedef void (*on_sys_unshare_enter_t)(CPUState* env,target_ulong pc,uint32_t unshare_flags);
typedef void (*on_sys_pciconfig_write_enter_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_getgroups_return_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_inotify_rm_watch_return_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t wd);
typedef void (*on_sys_openat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_setfsuid_return_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_request_key_enter_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _callout_info,uint32_t destringid);
typedef void (*on_sys_getppid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getcwd_return_t)(CPUState* env,target_ulong pc,target_ulong buf,uint32_t size);
typedef void (*on_sys_fstatfs64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t sz,target_ulong buf);
typedef void (*on_sys_lchown_return_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_arm_fadvise64_64_enter_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t advice,uint64_t offset,uint64_t len);
typedef void (*on_sys_close_enter_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_recvmsg_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_connect_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_llseek_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset_high,uint32_t offset_low,target_ulong result,uint32_t origin);
typedef void (*on_sys_readahead_return_t)(CPUState* env,target_ulong pc,int32_t fd,uint64_t offset,uint32_t count);
typedef void (*on_sys_fsetxattr_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_capget_enter_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong dataptr);
typedef void (*on_sys_eventfd2_return_t)(CPUState* env,target_ulong pc,uint32_t count,int32_t flags);
typedef void (*on_sys_mprotect_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t prot);
typedef void (*on_sys_setxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_fsync_return_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_pwrite64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_sendfile64_return_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_truncate64_enter_t)(CPUState* env,target_ulong pc,target_ulong path,uint64_t length);
typedef void (*on_sys_setitimer_return_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value,target_ulong ovalue);
typedef void (*on_sys_io_submit_return_t)(CPUState* env,target_ulong pc,uint32_t arg0,int32_t arg1,target_ulong arg2);
typedef void (*on_sys_getpeername_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_getdents64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_io_destroy_return_t)(CPUState* env,target_ulong pc,uint32_t ctx);
typedef void (*on_sys_newstat_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_inotify_init_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_prctl_enter_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_sched_getaffinity_return_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_select_enter_t)(CPUState* env,target_ulong pc,int32_t n,target_ulong inp,target_ulong outp,target_ulong exp,target_ulong tvp);
typedef void (*on_sys_readahead_enter_t)(CPUState* env,target_ulong pc,int32_t fd,uint64_t offset,uint32_t count);
typedef void (*on_sys_chown_return_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_ftruncate64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint64_t length);
typedef void (*on_sys_symlink_return_t)(CPUState* env,target_ulong pc,target_ulong old,target_ulong anew);
typedef void (*on_sys_read_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_lchown_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_sendto_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,int32_t arg5);
typedef void (*on_sys_inotify_add_watch_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong path,uint32_t mask);
typedef void (*on_sys_kexec_load_enter_t)(CPUState* env,target_ulong pc,uint32_t entry,uint32_t nr_segments,target_ulong segments,uint32_t flags);
typedef void (*on_sys_times_return_t)(CPUState* env,target_ulong pc,target_ulong tbuf);
typedef void (*on_sys_signalfd_return_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask);
typedef void (*on_sys_pipe2_return_t)(CPUState* env,target_ulong pc,target_ulong arg0,int32_t arg1);
typedef void (*on_sys_dup2_return_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd);
typedef void (*on_all_sys_linux_arm_enter_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_sys_umask_return_t)(CPUState* env,target_ulong pc,int32_t mask);
typedef void (*on_sys_newlstat_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_tee_enter_t)(CPUState* env,target_ulong pc,int32_t fdin,int32_t fdout,uint32_t len,uint32_t flags);
typedef void (*on_sys_epoll_create_return_t)(CPUState* env,target_ulong pc,int32_t size);
typedef void (*on_sys_mq_notify_enter_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong notification);
typedef void (*on_sys_setsid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_restart_syscall_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_futex_return_t)(CPUState* env,target_ulong pc,target_ulong uaddr,int32_t op,uint32_t val,target_ulong utime,target_ulong uaddr2,uint32_t val3);
typedef void (*on_sys_brk_enter_t)(CPUState* env,target_ulong pc,uint32_t brk);
typedef void (*on_sys_fchown16_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_acct_enter_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_fchownat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t user,uint32_t group,int32_t flag);
typedef void (*on_sys_fcntl64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_get_mempolicy_return_t)(CPUState* env,target_ulong pc,target_ulong policy,target_ulong nmask,uint32_t maxnode,uint32_t addr,uint32_t flags);
typedef void (*on_sys_sysinfo_enter_t)(CPUState* env,target_ulong pc,target_ulong info);
typedef void (*on_sys_lremovexattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_truncate_enter_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t length);
typedef void (*on_sys_pipe2_enter_t)(CPUState* env,target_ulong pc,target_ulong arg0,int32_t arg1);
typedef void (*on_sys_rt_sigpending_enter_t)(CPUState* env,target_ulong pc,target_ulong set,uint32_t sigsetsize);
typedef void (*on_sys_exit_group_return_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_setrlimit_return_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_fremovexattr_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name);
typedef void (*on_sys_adjtimex_return_t)(CPUState* env,target_ulong pc,target_ulong txc_p);
typedef void (*on_sys_setresgid_return_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_clock_getres_enter_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_readlinkat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_clock_settime_enter_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_sched_get_priority_max_return_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_send_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_futimesat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_pread64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_mkdir_enter_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_swapoff_return_t)(CPUState* env,target_ulong pc,target_ulong specialfile);
typedef void (*on_sys_sysinfo_return_t)(CPUState* env,target_ulong pc,target_ulong info);
typedef void (*on_sys_getsockopt_enter_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,target_ulong optlen);
typedef void (*on_ARM_user26_mode_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_ARM_user26_mode_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getpeername_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_ARM_set_tls_return_t)(CPUState* env,target_ulong pc,uint32_t arg);
typedef void (*on_sys_munlock_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_dup2_enter_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd);
typedef void (*on_sys_readlink_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_pciconfig_iobase_return_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t bus,uint32_t devfn);
typedef void (*on_sys_chown16_return_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_setfsgid_return_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_exit_enter_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_mq_notify_return_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong notification);
typedef void (*on_sys_getpid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sched_setaffinity_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_symlinkat_enter_t)(CPUState* env,target_ulong pc,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_llistxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_pause_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_nfsservctl_return_t)(CPUState* env,target_ulong pc,int32_t cmd,target_ulong arg,target_ulong res);
typedef void (*on_sys_recv_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_setreuid16_return_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_mkdir_return_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_recvmsg_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_socketpair_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2,target_ulong arg3);
typedef void (*on_sys_setreuid_enter_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_mq_timedreceive_return_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,target_ulong msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_mkdirat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t mode);
typedef void (*on_sys_mount_return_t)(CPUState* env,target_ulong pc,target_ulong dev_name,target_ulong dir_name,target_ulong type,uint32_t flags,target_ulong data_arg);
typedef void (*on_sys_gettimeofday_return_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_setgroups16_enter_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_ptrace_enter_t)(CPUState* env,target_ulong pc,int32_t request,int32_t pid,int32_t addr,int32_t data_arg);
typedef void (*on_ARM_null_segfault_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_removexattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_fstatat64_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong statbuf,int32_t flag);
typedef void (*on_sys_socketpair_return_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2,target_ulong arg3);
typedef void (*on_sys_dup_enter_t)(CPUState* env,target_ulong pc,uint32_t fildes);
typedef void (*on_sys_lseek_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset,uint32_t origin);
typedef void (*on_sys_msgsnd_enter_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgflg);
typedef void (*on_clone_return_t)(CPUState* env,target_ulong pc,uint32_t clone_flags,uint32_t newsp,target_ulong parent_tidptr,int32_t tls_val,target_ulong child_tidptr,target_ulong regs);
typedef void (*on_sys_sched_get_priority_min_return_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_llistxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_unlink_enter_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_sched_setscheduler_return_t)(CPUState* env,target_ulong pc,uint32_t pid,int32_t policy,target_ulong param);
typedef void (*on_sys_settimeofday_enter_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_semget_return_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t nsems,int32_t semflg);
typedef void (*on_sys_uselib_return_t)(CPUState* env,target_ulong pc,target_ulong library);
typedef void (*on_fork_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_ARM_null_segfault_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fchmod_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t mode);
typedef void (*on_sys_mlockall_return_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_fchown16_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_rmdir_enter_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_mknodat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_pipe_return_t)(CPUState* env,target_ulong pc,target_ulong arg0);
typedef void (*on_sys_setreuid_return_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_prctl_return_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_epoll_create1_return_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_socket_return_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2);
typedef void (*on_sys_clock_gettime_return_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_get_robust_list_return_t)(CPUState* env,target_ulong pc,int32_t pid,target_ulong head_ptr,target_ulong len_ptr);
typedef void (*on_sys_chdir_return_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_epoll_ctl_enter_t)(CPUState* env,target_ulong pc,int32_t epfd,int32_t op,int32_t fd,target_ulong event);
typedef void (*on_sys_truncate_return_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t length);
typedef void (*on_sys_chmod_return_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t mode);
typedef void (*on_sys_creat_enter_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_utimes_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_setgid16_return_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_getresgid16_enter_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_chdir_enter_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_uselib_enter_t)(CPUState* env,target_ulong pc,target_ulong library);
typedef void (*on_sys_getsockname_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_getuid16_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_eventfd_return_t)(CPUState* env,target_ulong pc,uint32_t count);
typedef void (*on_sys_timer_gettime_return_t)(CPUState* env,target_ulong pc,uint32_t timer_id,target_ulong setting);
typedef void (*on_sys_msync_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t flags);
typedef void (*on_sys_timer_settime_return_t)(CPUState* env,target_ulong pc,uint32_t timer_id,int32_t flags,target_ulong new_setting,target_ulong old_setting);
typedef void (*on_sys_flock_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd);
typedef void (*on_sys_madvise_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t behavior);
typedef void (*on_sys_signalfd_enter_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask);
typedef void (*on_sys_getrusage_enter_t)(CPUState* env,target_ulong pc,int32_t who,target_ulong ru);
typedef void (*on_sys_getxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_init_module_enter_t)(CPUState* env,target_ulong pc,target_ulong umod,uint32_t len,target_ulong uargs);
typedef void (*on_sys_remap_file_pages_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t size,uint32_t prot,uint32_t pgoff,uint32_t flags);
typedef void (*on_sys_sched_setaffinity_return_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_ftruncate64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint64_t length);
typedef void (*on_sys_msgget_return_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t msgflg);
typedef void (*on_sys_getegid16_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_shmget_return_t)(CPUState* env,target_ulong pc,uint32_t key,uint32_t size,int32_t flag);
typedef void (*on_sys_futex_enter_t)(CPUState* env,target_ulong pc,target_ulong uaddr,int32_t op,uint32_t val,target_ulong utime,target_ulong uaddr2,uint32_t val3);
typedef void (*on_sys_getdents_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_ioprio_get_return_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_ARM_cmpxchg_enter_t)(CPUState* env,target_ulong pc,uint32_t val,uint32_t src,target_ulong dest);
typedef void (*on_sys_pciconfig_read_enter_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_eventfd_enter_t)(CPUState* env,target_ulong pc,uint32_t count);
typedef void (*on_sys_sched_setscheduler_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,int32_t policy,target_ulong param);
typedef void (*on_sys_ustat_enter_t)(CPUState* env,target_ulong pc,uint32_t dev,target_ulong ubuf);
typedef void (*on_sys_linkat_enter_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname,int32_t flags);
typedef void (*on_sys_vhangup_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sendfile_return_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_newuname_enter_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_settimeofday_return_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_timer_getoverrun_return_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_fchown_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_setitimer_enter_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value,target_ulong ovalue);
typedef void (*on_sys_mprotect_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t prot);
typedef void (*on_sys_timerfd_settime_return_t)(CPUState* env,target_ulong pc,int32_t ufd,int32_t flags,target_ulong utmr,target_ulong otmr);
typedef void (*on_sys_rt_sigpending_return_t)(CPUState* env,target_ulong pc,target_ulong set,uint32_t sigsetsize);
typedef void (*on_sys_setxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_mq_timedsend_return_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,uint32_t msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_swapon_return_t)(CPUState* env,target_ulong pc,target_ulong specialfile,int32_t swap_flags);
typedef void (*on_sys_sendfile64_enter_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_mlockall_enter_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_listen_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_creat_return_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_bdflush_enter_t)(CPUState* env,target_ulong pc,int32_t func,int32_t data_arg);
typedef void (*on_sys_mkdirat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t mode);
typedef void (*on_sys_dup3_enter_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd,int32_t flags);
typedef void (*on_sys_epoll_wait_enter_t)(CPUState* env,target_ulong pc,int32_t epfd,target_ulong events,int32_t maxevents,int32_t timeout);
typedef void (*on_sys_munmap_return_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len);
typedef void (*on_sys_rmdir_return_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_timer_delete_enter_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_statfs_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf);
typedef void (*on_sys_getresgid_enter_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_dup_return_t)(CPUState* env,target_ulong pc,uint32_t fildes);
typedef void (*on_sys_geteuid16_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_arm_fadvise64_64_return_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t advice,uint64_t offset,uint64_t len);
typedef void (*on_sys_mq_open_return_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t oflag,uint32_t mode,target_ulong attr);
typedef void (*on_sys_msgctl_return_t)(CPUState* env,target_ulong pc,int32_t msqid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_utimes_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_getpgrp_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setsockopt_enter_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,int32_t optlen);
typedef void (*on_sys_bind_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_capget_return_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong dataptr);
typedef void (*on_sys_newfstat_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_rt_sigprocmask_return_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset,uint32_t sigsetsize);
typedef void (*on_sys_sendfile_enter_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_vfork_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_ARM_usr32_mode_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_access_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode);
typedef void (*on_sys_semctl_enter_t)(CPUState* env,target_ulong pc,int32_t semid,int32_t semnum,int32_t cmd,uint32_t arg);
typedef void (*on_sys_msgrcv_return_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgtyp,int32_t msgflg);
typedef void (*on_sys_sched_getscheduler_enter_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_pciconfig_iobase_enter_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t bus,uint32_t devfn);
typedef void (*on_sigsuspend_enter_t)(CPUState* env,target_ulong pc,int32_t restart,uint32_t oldmask,uint32_t mask);
typedef void (*on_sys_poll_enter_t)(CPUState* env,target_ulong pc,target_ulong ufds,uint32_t nfds,int32_t timeout);
typedef void (*on_sys_io_cancel_return_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,target_ulong iocb,target_ulong result);
typedef void (*on_sys_statfs64_enter_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t sz,target_ulong buf);
typedef void (*on_sys_flock_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd);
typedef void (*on_sys_remap_file_pages_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t size,uint32_t prot,uint32_t pgoff,uint32_t flags);
typedef void (*on_sys_newuname_return_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_geteuid16_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getgid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_set_tid_address_enter_t)(CPUState* env,target_ulong pc,target_ulong tidptr);
typedef void (*on_sys_timer_create_enter_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong timer_event_spec,target_ulong created_timer_id);
typedef void (*on_sys_epoll_wait_return_t)(CPUState* env,target_ulong pc,int32_t epfd,target_ulong events,int32_t maxevents,int32_t timeout);
typedef void (*on_sys_sysctl_return_t)(CPUState* env,target_ulong pc,target_ulong args);
typedef void (*on_sys_io_cancel_enter_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,target_ulong iocb,target_ulong result);
typedef void (*on_sys_sched_get_priority_max_enter_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_newfstat_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_set_robust_list_return_t)(CPUState* env,target_ulong pc,target_ulong head,uint32_t len);
typedef void (*on_sys_move_pages_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t nr_pages,target_ulong pages,target_ulong nodes,target_ulong status,int32_t flags);
typedef void (*on_sys_ioprio_set_enter_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t ioprio);
typedef void (*on_sys_mq_timedsend_enter_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,uint32_t msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_statfs64_return_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t sz,target_ulong buf);
typedef void (*on_sys_read_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_shmctl_enter_t)(CPUState* env,target_ulong pc,int32_t shmid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_setdomainname_return_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_waitid_return_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t pid,target_ulong infop,int32_t options,target_ulong ru);
typedef void (*on_sys_unshare_return_t)(CPUState* env,target_ulong pc,uint32_t unshare_flags);
typedef void (*on_sys_setresuid_return_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_fstatfs_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf);
typedef void (*on_do_sigaltstack_return_t)(CPUState* env,target_ulong pc,target_ulong uss,target_ulong uoss);
typedef void (*on_sys_getresuid16_return_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_msgctl_enter_t)(CPUState* env,target_ulong pc,int32_t msqid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_kill_return_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_tgkill_enter_t)(CPUState* env,target_ulong pc,int32_t tgid,int32_t pid,int32_t sig);
typedef void (*on_sys_set_mempolicy_enter_t)(CPUState* env,target_ulong pc,int32_t mode,target_ulong nmask,uint32_t maxnode);
typedef void (*on_sys_timer_delete_return_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_getpriority_enter_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_ioprio_set_return_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t ioprio);
typedef void (*on_sys_semtimedop_enter_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops,target_ulong timeout);
typedef void (*on_sys_sendto_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,int32_t arg5);
typedef void (*on_sys_add_key_return_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _payload,uint32_t plen,uint32_t destringid);
typedef void (*on_sys_llseek_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset_high,uint32_t offset_low,target_ulong result,uint32_t origin);
typedef void (*on_sys_timer_getoverrun_enter_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_sysctl_enter_t)(CPUState* env,target_ulong pc,target_ulong args);
typedef void (*on_sys_fallocate_enter_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t mode,uint64_t offset,uint64_t len);
typedef void (*on_sys_setgroups_enter_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_stat64_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_rt_sigprocmask_enter_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset,uint32_t sigsetsize);
typedef void (*on_sys_fgetxattr_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_write_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_lsetxattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_setuid16_return_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_setreuid16_enter_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sigsuspend_return_t)(CPUState* env,target_ulong pc,int32_t restart,uint32_t oldmask,uint32_t mask);
typedef void (*on_sys_nfsservctl_enter_t)(CPUState* env,target_ulong pc,int32_t cmd,target_ulong arg,target_ulong res);
typedef void (*on_sys_acct_return_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_fcntl_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_setresuid_enter_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_getitimer_return_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value);
typedef void (*on_sys_getuid16_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setgid_enter_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_fchdir_enter_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_fremovexattr_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name);
typedef void (*on_sys_signalfd4_return_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask,int32_t flags);
typedef void (*on_sys_epoll_create_enter_t)(CPUState* env,target_ulong pc,int32_t size);
typedef void (*on_sys_setrlimit_enter_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_select_return_t)(CPUState* env,target_ulong pc,int32_t n,target_ulong inp,target_ulong outp,target_ulong exp,target_ulong tvp);
typedef void (*on_sys_getresuid16_enter_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_do_mmap2_enter_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len,uint32_t prot,uint32_t flags,uint32_t fd,uint32_t pgoff);
typedef void (*on_sys_bind_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_ptrace_return_t)(CPUState* env,target_ulong pc,int32_t request,int32_t pid,int32_t addr,int32_t data_arg);
typedef void (*on_sys_setpriority_enter_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t niceval);
typedef void (*on_sys_timerfd_gettime_return_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong otmr);
typedef void (*on_sys_getsid_return_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_munlockall_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getegid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setregid16_return_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_arm_mremap_enter_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t old_len,uint32_t new_len,uint32_t flags,uint32_t new_addr);
typedef void (*on_sys_recvfrom_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,target_ulong arg5);
typedef void (*on_sys_getitimer_enter_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value);
typedef void (*on_sys_getcpu_return_t)(CPUState* env,target_ulong pc,target_ulong cpu,target_ulong node,target_ulong cache);
typedef void (*on_sys_waitid_enter_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t pid,target_ulong infop,int32_t options,target_ulong ru);
typedef void (*on_sys_tee_return_t)(CPUState* env,target_ulong pc,int32_t fdin,int32_t fdout,uint32_t len,uint32_t flags);
typedef void (*on_sys_clock_gettime_enter_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_sync_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_arm_mremap_return_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t old_len,uint32_t new_len,uint32_t flags,uint32_t new_addr);
typedef void (*on_sys_getpid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_splice_return_t)(CPUState* env,target_ulong pc,int32_t fd_in,target_ulong off_in,int32_t fd_out,target_ulong off_out,uint32_t len,uint32_t flags);
typedef void (*on_sys_setfsgid_enter_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_io_setup_return_t)(CPUState* env,target_ulong pc,uint32_t nr_reqs,target_ulong ctx);
typedef void (*on_sys_flistxattr_enter_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong list,uint32_t size);
typedef void (*on_sys_bdflush_return_t)(CPUState* env,target_ulong pc,int32_t func,int32_t data_arg);
typedef void (*on_sys_nanosleep_return_t)(CPUState* env,target_ulong pc,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_setsid_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_mbind_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t mode,target_ulong nmask,uint32_t maxnode,uint32_t flags);
typedef void (*on_sys_mq_unlink_return_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_mincore_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,target_ulong vec);
typedef void (*on_sys_mincore_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,target_ulong vec);
typedef void (*on_sys_send_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_fchmodat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t mode);
typedef void (*on_sys_sched_yield_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_personality_enter_t)(CPUState* env,target_ulong pc,int32_t personality);
typedef void (*on_sys_fstatfs_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf);
typedef void (*on_sys_sysfs_return_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg1,uint32_t arg2);
typedef void (*on_ARM_cmpxchg_return_t)(CPUState* env,target_ulong pc,uint32_t val,uint32_t src,target_ulong dest);
typedef void (*on_sys_init_module_return_t)(CPUState* env,target_ulong pc,target_ulong umod,uint32_t len,target_ulong uargs);
typedef void (*on_sys_lchown16_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_quotactl_enter_t)(CPUState* env,target_ulong pc,uint32_t cmd,target_ulong special,uint32_t id,target_ulong addr);
typedef void (*on_sys_write_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_getresgid16_return_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_utimensat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes,int32_t flags);
typedef void (*on_sys_unlinkat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t flag);
typedef void (*on_sys_eventfd2_enter_t)(CPUState* env,target_ulong pc,uint32_t count,int32_t flags);
typedef void (*on_sys_sync_file_range2_enter_t)(CPUState* env,target_ulong pc,int32_t fd,uint32_t flags,uint64_t offset,uint64_t nbytes);
typedef void (*on_sys_getgid16_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_semget_enter_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t nsems,int32_t semflg);
typedef void (*on_sys_sigpending_return_t)(CPUState* env,target_ulong pc,target_ulong set);
typedef void (*on_sys_nice_return_t)(CPUState* env,target_ulong pc,int32_t increment);
typedef void (*on_sys_ftruncate_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t length);
typedef void (*on_sys_getsockopt_return_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,target_ulong optlen);
typedef void (*on_sys_sched_setparam_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_listen_return_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_mbind_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t mode,target_ulong nmask,uint32_t maxnode,uint32_t flags);
typedef void (*on_sys_reboot_return_t)(CPUState* env,target_ulong pc,int32_t magic1,int32_t magic2,uint32_t cmd,target_ulong arg);
typedef void (*on_sys_setuid_return_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_lchown16_return_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_fchmodat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t mode);
typedef void (*on_sys_swapon_enter_t)(CPUState* env,target_ulong pc,target_ulong specialfile,int32_t swap_flags);
typedef void (*on_sys_msync_return_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t flags);
typedef void (*on_sys_gettid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_renameat_enter_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_setgid16_enter_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_umask_enter_t)(CPUState* env,target_ulong pc,int32_t mask);
typedef void (*on_sys_readv_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_accept_return_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_adjtimex_enter_t)(CPUState* env,target_ulong pc,target_ulong txc_p);
typedef void (*on_sys_getgroups16_return_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_getpriority_return_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_readv_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_fstat64_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_clone_enter_t)(CPUState* env,target_ulong pc,uint32_t clone_flags,uint32_t newsp,target_ulong parent_tidptr,int32_t tls_val,target_ulong child_tidptr,target_ulong regs);
typedef void (*on_unknown_sys_linux_arm_return_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_sys_wait4_enter_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong stat_addr,int32_t options,target_ulong ru);
typedef void (*on_sys_getrlimit_return_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_dup3_return_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd,int32_t flags);
typedef void (*on_sys_wait4_return_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong stat_addr,int32_t options,target_ulong ru);
typedef void (*on_sys_io_getevents_return_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,int32_t min_nr,int32_t nr,target_ulong events,target_ulong timeout);
typedef void (*on_sys_syslog_return_t)(CPUState* env,target_ulong pc,int32_t type,target_ulong buf,int32_t len);
typedef void (*on_sys_inotify_init1_return_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_sched_getscheduler_return_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_linkat_return_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname,int32_t flags);
typedef void (*on_sys_setfsuid_enter_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_semop_enter_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops);
typedef void (*on_sys_clock_nanosleep_enter_t)(CPUState* env,target_ulong pc,uint32_t which_clock,int32_t flags,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_futimesat_enter_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_lookup_dcookie_return_t)(CPUState* env,target_ulong pc,uint64_t cookie64,target_ulong buf,uint32_t len);
typedef void (*on_ARM_cacheflush_enter_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t end,uint32_t flags);
typedef void (*on_sys_epoll_create1_enter_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_msgrcv_enter_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgtyp,int32_t msgflg);
typedef void (*on_sys_vmsplice_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong iov,uint32_t nr_segs,uint32_t flags);
typedef void (*on_sys_readlinkat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_pciconfig_write_return_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_rt_sigtimedwait_return_t)(CPUState* env,target_ulong pc,target_ulong uthese,target_ulong uinfo,target_ulong uts,uint32_t sigsetsize);
typedef void (*on_sys_msgsnd_return_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgflg);
typedef void (*on_sys_rename_return_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_open_return_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_faccessat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode);
typedef void (*on_sys_lseek_return_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset,uint32_t origin);
typedef void (*on_sys_munlockall_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_exit_group_enter_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_rt_sigqueueinfo_enter_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig,target_ulong uinfo);
typedef void (*on_sys_tkill_return_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_ARM_usr32_mode_enter_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setgroups_return_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_fdatasync_enter_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_rt_sigsuspend_return_t)(CPUState* env,target_ulong pc,target_ulong unewset,uint32_t sigsetsize);
typedef void (*on_sys_inotify_rm_watch_enter_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t wd);
typedef void (*on_sys_fstatfs64_enter_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t sz,target_ulong buf);
typedef void (*on_sys_lstat64_return_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_mq_timedreceive_enter_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,target_ulong msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_shmdt_enter_t)(CPUState* env,target_ulong pc,target_ulong shmaddr);
typedef void (*on_sys_lremovexattr_enter_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_chown16_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_chown_enter_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_shutdown_enter_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_tkill_enter_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_listxattr_return_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_delete_module_enter_t)(CPUState* env,target_ulong pc,target_ulong name_user,uint32_t flags);
typedef void (*on_sys_unlinkat_return_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t flag);
typedef void (*on_sys_writev_return_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sigaction_return_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact);
typedef void (*on_sys_getuid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setgid_return_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_setregid16_enter_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_geteuid_return_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fsetxattr_return_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
#endif
