#ifdef TARGET_I386
typedef void (*on_NtReplaceKey_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t Key,uint32_t ReplacedObjectAttributes);
typedef void (*on_NtCreateUserProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ThreadHandle,uint32_t ProcessDesiredAccess,uint32_t ThreadDesiredAccess,uint32_t ProcessObjectAttributes,uint32_t ThreadObjectAttributes,uint32_t ProcessFlags,uint32_t ThreadFlags,uint32_t ProcessParameters,uint32_t CreateInfo,uint32_t AttributeList);
typedef void (*on_NtAllocateVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t ZeroBits,uint32_t RegionSize,uint32_t AllocationType,uint32_t Protect);
typedef void (*on_NtModifyBootEntry_enter_t)(CPUState* env,target_ulong pc,uint32_t BootEntry);
typedef void (*on_NtAssignProcessToJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t ProcessHandle);
typedef void (*on_NtSetVolumeInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FsInformation,uint32_t Length,uint32_t FsInformationClass);
typedef void (*on_NtAreMappedFilesTheSame_enter_t)(CPUState* env,target_ulong pc,uint32_t File1MappedAsAnImage,uint32_t File2MappedAsFile);
typedef void (*on_NtReleaseKeyedEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t Key,uint32_t Alertable,uint32_t Timeout);
typedef void (*on_all_sys_windows7_x86_enter_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_NtCreateFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t AllocationSize,uint32_t FileAttributes,uint32_t ShareAccess,uint32_t CreateDisposition,uint32_t CreateOptions,uint32_t EaBuffer,uint32_t EaLength);
typedef void (*on_NtCreateJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t PreviousState);
typedef void (*on_NtSetIoCompletion_return_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionPortHandle,uint32_t CompletionKey,uint32_t CompletionContext,uint32_t CompletionStatus,uint32_t CompletionInformation);
typedef void (*on_NtReplyWaitReplyPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ReplyMessage);
typedef void (*on_NtRestoreKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle,uint32_t RestoreFlags);
typedef void (*on_NtQuerySystemInformation_return_t)(CPUState* env,target_ulong pc,uint32_t SystemInformationClass,uint32_t SystemInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtSecureConnectPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortName,uint32_t SecurityQos,uint32_t ClientView,uint32_t Sid,uint32_t ServerView,uint32_t MaxMessageLength,uint32_t ConnectionInformation,uint32_t ConnectionInformationLength);
typedef void (*on_NtReadFileScatter_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t UserIoStatusBlock,uint32_t BufferDescription,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtQueryInformationPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortInformationClass,uint32_t PortInformation,uint32_t PortInformationLength,uint32_t ReturnLength);
typedef void (*on_NtQueryIoCompletion_return_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,uint32_t IoCompletionInformationClass,uint32_t IoCompletionInformation,uint32_t IoCompletionInformationLength,uint32_t ResultLength);
typedef void (*on_NtQueryDirectoryObject_return_t)(CPUState* env,target_ulong pc,uint32_t DirectoryHandle,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnSingleEntry,uint32_t RestartScan,uint32_t Context,uint32_t ReturnLength);
typedef void (*on_NtAlertResumeThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t SuspendCount);
typedef void (*on_NtOpenKeyedEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetDefaultLocale_enter_t)(CPUState* env,target_ulong pc,uint32_t UserProfile,uint32_t DefaultLocaleId);
typedef void (*on_NtRaiseHardError_return_t)(CPUState* env,target_ulong pc,uint32_t ErrorStatus,uint32_t NumberOfParameters,uint32_t UnicodeStringParameterMask,uint32_t Parameters,uint32_t ValidResponseOptions,uint32_t Response);
typedef void (*on_NtYieldExecution_return_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtListenPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ConnectionRequest);
typedef void (*on_NtSetQuotaInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtSetInformationKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t KeyInformationLength);
typedef void (*on_NtClearEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle);
typedef void (*on_NtQueryTimer_return_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t TimerInformationClass,uint32_t TimerInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtOpenSemaphore_return_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t DesiredAcces,uint32_t ObjectAttributes);
typedef void (*on_NtPrivilegeCheck_return_t)(CPUState* env,target_ulong pc,uint32_t ClientToken,uint32_t RequiredPrivileges,uint32_t Result);
typedef void (*on_NtSetSystemInformation_enter_t)(CPUState* env,target_ulong pc,uint32_t SystemInformationClass,uint32_t SystemInformation,uint32_t SystemInformationLength);
typedef void (*on_NtUnlockVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToUnlock,uint32_t NumberOfBytesUnlocked);
typedef void (*on_NtCreateTimer_enter_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TimerType);
typedef void (*on_NtCreateUserProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ThreadHandle,uint32_t ProcessDesiredAccess,uint32_t ThreadDesiredAccess,uint32_t ProcessObjectAttributes,uint32_t ThreadObjectAttributes,uint32_t ProcessFlags,uint32_t ThreadFlags,uint32_t ProcessParameters,uint32_t CreateInfo,uint32_t AttributeList);
typedef void (*on_NtQueryDirectoryFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass,uint32_t ReturnSingleEntry,uint32_t FileName,uint32_t RestartScan);
typedef void (*on_NtQuerySymbolicLinkObject_return_t)(CPUState* env,target_ulong pc,uint32_t SymLinkObjHandle,uint32_t LinkTarget,uint32_t DataWritten);
typedef void (*on_NtSetInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass);
typedef void (*on_NtCreateProcessEx_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ParentProcess,uint32_t Flags,uint32_t SectionHandle,uint32_t DebugPort,uint32_t ExceptionPort,uint32_t InJob);
typedef void (*on_NtCreateIoCompletion_enter_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t NumberOfConcurrentThreads);
typedef void (*on_NtOpenKeyEx_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t OpenOptions);
typedef void (*on_NtCreateThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ProcessHandle,uint32_t ClientId,uint32_t ThreadContext,uint32_t UserStack,uint32_t CreateSuspended);
typedef void (*on_NtFindAtom_enter_t)(CPUState* env,target_ulong pc,uint32_t AtomName,uint32_t AtomNameLength,uint32_t Atom);
typedef void (*on_NtOpenTimer_return_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtReleaseSemaphore_return_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,int32_t ReleaseCount,uint32_t PreviousCount);
typedef void (*on_NtQueryIntervalProfile_enter_t)(CPUState* env,target_ulong pc,uint32_t ProfileSource,uint32_t Interval);
typedef void (*on_NtOpenSection_enter_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateJobSet_return_t)(CPUState* env,target_ulong pc,uint32_t NumJob,uint32_t UserJobSet,uint32_t Flags);
typedef void (*on_NtMakeTemporaryObject_enter_t)(CPUState* env,target_ulong pc,uint32_t Handle);
typedef void (*on_NtSetHighWaitLowEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtPowerInformation_return_t)(CPUState* env,target_ulong pc,uint32_t PowerInformationLevel,uint32_t InputBuffer,uint32_t InputBufferLength,uint32_t OutputBuffer,uint32_t OutputBufferLength);
typedef void (*on_NtReleaseSemaphore_enter_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,int32_t ReleaseCount,uint32_t PreviousCount);
typedef void (*on_NtMapViewOfSection_return_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t ZeroBits,uint32_t CommitSize,uint32_t SectionOffset,uint32_t ViewSize,uint32_t InheritDisposition,uint32_t AllocationType,uint32_t AccessProtection);
typedef void (*on_NtPlugPlayControl_enter_t)(CPUState* env,target_ulong pc,uint32_t PlugPlayControlClass,uint32_t Buffer,uint32_t BufferSize);
typedef void (*on_NtQueryInformationThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadInformationClass,uint32_t ThreadInformation,uint32_t ThreadInformationLength,uint32_t ReturnLength);
typedef void (*on_NtAdjustGroupsToken_return_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t ResetToDefault,uint32_t NewState,uint32_t BufferLength,uint32_t PreviousState,uint32_t ReturnLength);
typedef void (*on_NtUnloadKeyEx_enter_t)(CPUState* env,target_ulong pc,uint32_t TargetKey,uint32_t Event);
typedef void (*on_NtSetLowWaitHighEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPair);
typedef void (*on_NtSetInformationToken_enter_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t TokenInformationClass,uint32_t TokenInformation,uint32_t TokenInformationLength);
typedef void (*on_NtPrivilegedServiceAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t ServiceName,uint32_t ClientToken,uint32_t Privileges,uint32_t AccessGranted);
typedef void (*on_NtReplyWaitReceivePort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,target_ulong PortContext,uint32_t ReplyMessage,uint32_t ReceiveMessage);
typedef void (*on_NtFindAtom_return_t)(CPUState* env,target_ulong pc,uint32_t AtomName,uint32_t AtomNameLength,uint32_t Atom);
typedef void (*on_NtMapViewOfSection_enter_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t ZeroBits,uint32_t CommitSize,uint32_t SectionOffset,uint32_t ViewSize,uint32_t InheritDisposition,uint32_t AllocationType,uint32_t AccessProtection);
typedef void (*on_NtWaitForKeyedEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t Key,uint32_t Alertable,uint32_t Timeout);
typedef void (*on_NtQueryInstallUILanguage_enter_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtSetSystemTime_return_t)(CPUState* env,target_ulong pc,uint32_t SystemTime,uint32_t NewSystemTime);
typedef void (*on_NtDeleteFile_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes);
typedef void (*on_NtMakeTemporaryObject_return_t)(CPUState* env,target_ulong pc,uint32_t Handle);
typedef void (*on_NtImpersonateThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadToImpersonate,uint32_t SecurityQualityOfService);
typedef void (*on_NtUnmapViewOfSection_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress);
typedef void (*on_NtQueryMutant_enter_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t MutantInformationClass,uint32_t MutantInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtLockVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToLock,uint32_t NumberOfBytesLocked);
typedef void (*on_NtFlushInstructionCache_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToFlush);
typedef void (*on_NtSetDefaultUILanguage_enter_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtWaitForKeyedEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t Key,uint32_t Alertable,uint32_t Timeout);
typedef void (*on_NtSetSecurityObject_return_t)(CPUState* env,target_ulong pc,uint32_t Handle,uint32_t SecurityInformation,uint32_t SecurityDescriptor);
typedef void (*on_NtExtendSection_return_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t NewMaximumSize);
typedef void (*on_NtReplyWaitReceivePortEx_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,target_ulong PortContext,uint32_t ReplyMessage,uint32_t ReceiveMessage,uint32_t Timeout);
typedef void (*on_NtCreateEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtWriteFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtWriteVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t Buffer,uint32_t NumberOfBytesToWrite,uint32_t NumberOfBytesWritten);
typedef void (*on_NtReplyWaitReceivePortEx_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,target_ulong PortContext,uint32_t ReplyMessage,uint32_t ReceiveMessage,uint32_t Timeout);
typedef void (*on_NtRestoreKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle,uint32_t RestoreFlags);
typedef void (*on_NtUnmapViewOfSection_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress);
typedef void (*on_NtCreateDebugObject_enter_t)(CPUState* env,target_ulong pc,uint32_t DebugHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t KillProcessOnExit);
typedef void (*on_NtInitiatePowerAction_enter_t)(CPUState* env,target_ulong pc,uint32_t SystemAction,uint32_t MinSystemState,uint32_t Flags,uint32_t Asynchronous);
typedef void (*on_NtWriteRequestData_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t Message,uint32_t Index,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnLength);
typedef void (*on_NtSetIntervalProfile_return_t)(CPUState* env,target_ulong pc,uint32_t Interval,uint32_t ClockSource);
typedef void (*on_NtQueryInformationAtom_return_t)(CPUState* env,target_ulong pc,uint32_t Atom,uint32_t AtomInformationClass,uint32_t AtomInformation,uint32_t AtomInformationLength,uint32_t ReturnLength);
typedef void (*on_NtOpenEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtMapUserPhysicalPagesScatter_return_t)(CPUState* env,target_ulong pc,target_ulong VirtualAddresses,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtQueryEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t EventInformationClass,uint32_t EventInformation,uint32_t EventInformationLength,uint32_t ReturnLength);
typedef void (*on_NtQuerySymbolicLinkObject_enter_t)(CPUState* env,target_ulong pc,uint32_t SymLinkObjHandle,uint32_t LinkTarget,uint32_t DataWritten);
typedef void (*on_NtReplyWaitReceivePort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,target_ulong PortContext,uint32_t ReplyMessage,uint32_t ReceiveMessage);
typedef void (*on_NtOpenProcessTokenEx_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t HandleAttributes,uint32_t TokenHandle);
typedef void (*on_NtQueryOpenSubKeys_enter_t)(CPUState* env,target_ulong pc,uint32_t TargetKey,uint32_t HandleCount);
typedef void (*on_NtSetEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t PreviousState);
typedef void (*on_NtAddAtom_enter_t)(CPUState* env,target_ulong pc,uint32_t AtomName,uint32_t AtomNameLength,uint32_t Atom);
typedef void (*on_NtCompressKey_return_t)(CPUState* env,target_ulong pc,uint32_t Key);
typedef void (*on_NtSetInformationDebugObject_return_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t InformationClass,uint32_t Information,uint32_t InformationLength,uint32_t ReturnLength);
typedef void (*on_NtOpenDirectoryObject_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtDeleteAtom_enter_t)(CPUState* env,target_ulong pc,uint32_t Atom);
typedef void (*on_NtQuerySection_enter_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t SectionInformationClass,uint32_t SectionInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtTerminateJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t ExitStatus);
typedef void (*on_NtPlugPlayControl_return_t)(CPUState* env,target_ulong pc,uint32_t PlugPlayControlClass,uint32_t Buffer,uint32_t BufferSize);
typedef void (*on_NtQueryInformationJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t JobInformationClass,uint32_t JobInformation,uint32_t JobInformationLength,uint32_t ReturnLength);
typedef void (*on_NtModifyBootEntry_return_t)(CPUState* env,target_ulong pc,uint32_t BootEntry);
typedef void (*on_NtOpenObjectAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ObjectTypeName,uint32_t ObjectName,uint32_t SecurityDescriptor,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t GrantedAccess,uint32_t Privileges,uint32_t ObjectCreation,uint32_t AccessGranted,uint32_t GenerateOnClose);
typedef void (*on_NtSetDefaultHardErrorPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle);
typedef void (*on_NtQueryQuotaInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ReturnSingleEntry,uint32_t SidList,uint32_t SidListLength,uint32_t StartSid,uint32_t RestartScan);
typedef void (*on_NtFsControlFile_enter_t)(CPUState* env,target_ulong pc,uint32_t DeviceHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t IoControlCode,uint32_t InputBuffer,uint32_t InputBufferSize,uint32_t OutputBuffer,uint32_t OutputBufferSize);
typedef void (*on_NtCreatePagingFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileName,uint32_t InitialSize,uint32_t MaxiumSize,uint32_t Reserved);
typedef void (*on_NtQueryInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass);
typedef void (*on_NtSetTimer_enter_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DueTime,uint32_t TimerApcRoutine,uint32_t TimerContext,uint32_t WakeTimer,int32_t Period,uint32_t PreviousState);
typedef void (*on_NtDeviceIoControlFile_enter_t)(CPUState* env,target_ulong pc,uint32_t DeviceHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t IoStatusBlock,uint32_t IoControlCode,uint32_t InputBuffer,uint32_t InputBufferSize,uint32_t OutputBuffer,uint32_t OutputBufferSize);
typedef void (*on_NtReadVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t Buffer,uint32_t NumberOfBytesToRead,uint32_t NumberOfBytesRead);
typedef void (*on_NtOpenIoCompletion_enter_t)(CPUState* env,target_ulong pc,uint32_t CompetionPort,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtDeleteFile_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes);
typedef void (*on_NtImpersonateThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadToImpersonate,uint32_t SecurityQualityOfService);
typedef void (*on_NtPrivilegedServiceAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t ServiceName,uint32_t ClientToken,uint32_t Privileges,uint32_t AccessGranted);
typedef void (*on_NtContinue_return_t)(CPUState* env,target_ulong pc,uint32_t Context,uint32_t TestAlert);
typedef void (*on_NtAcceptConnectPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortContext,uint32_t ConnectionRequest,uint32_t AcceptConnection,uint32_t ServerView,uint32_t ClientView);
typedef void (*on_NtSystemDebugControl_return_t)(CPUState* env,target_ulong pc,uint32_t ControlCode,uint32_t InputBuffer,uint32_t InputBufferLength,uint32_t OutputBuffer,uint32_t OutputBufferLength,uint32_t ReturnLength);
typedef void (*on_NtOpenSymbolicLinkObject_return_t)(CPUState* env,target_ulong pc,uint32_t SymbolicLinkHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateJobSet_enter_t)(CPUState* env,target_ulong pc,uint32_t NumJob,uint32_t UserJobSet,uint32_t Flags);
typedef void (*on_NtMapUserPhysicalPages_return_t)(CPUState* env,target_ulong pc,target_ulong VirtualAddresses,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtOpenProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ClientId);
typedef void (*on_NtCreateKeyedEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyedEventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t Flags);
typedef void (*on_NtCompareTokens_enter_t)(CPUState* env,target_ulong pc,uint32_t FirstTokenHandle,uint32_t SecondTokenHandle,uint32_t Equal);
typedef void (*on_NtAllocateLocallyUniqueId_return_t)(CPUState* env,target_ulong pc,target_ulong LocallyUniqueId);
typedef void (*on_NtQueryInstallUILanguage_return_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtWaitForSingleObject_return_t)(CPUState* env,target_ulong pc,uint32_t Object,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtSaveMergedKeys_return_t)(CPUState* env,target_ulong pc,uint32_t HighPrecedenceKeyHandle,uint32_t LowPrecedenceKeyHandle,uint32_t FileHandle);
typedef void (*on_NtRequestWaitReplyPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcReply,uint32_t LpcRequest);
typedef void (*on_NtNotifyChangeDirectoryFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferSize,uint32_t CompletionFilter,uint32_t WatchTree);
typedef void (*on_NtSetSystemPowerState_return_t)(CPUState* env,target_ulong pc,uint32_t SystemAction,uint32_t MinSystemState,uint32_t Flags);
typedef void (*on_NtAlertThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle);
typedef void (*on_NtSetSystemInformation_return_t)(CPUState* env,target_ulong pc,uint32_t SystemInformationClass,uint32_t SystemInformation,uint32_t SystemInformationLength);
typedef void (*on_NtCreateSemaphore_return_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,int32_t InitialCount,int32_t MaximumCount);
typedef void (*on_NtWriteVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t Buffer,uint32_t NumberOfBytesToWrite,uint32_t NumberOfBytesWritten);
typedef void (*on_NtDeleteObjectAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t GenerateOnClose);
typedef void (*on_NtCreateIoCompletion_return_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t NumberOfConcurrentThreads);
typedef void (*on_NtQuerySystemEnvironmentValue_return_t)(CPUState* env,target_ulong pc,uint32_t Name,uint32_t Value,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtCreateSection_return_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t MaximumSize,uint32_t SectionPageProtection,uint32_t AllocationAttributes,uint32_t FileHandle);
typedef void (*on_NtReleaseMutant_return_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t ReleaseCount);
typedef void (*on_NtCreateDebugObject_return_t)(CPUState* env,target_ulong pc,uint32_t DebugHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t KillProcessOnExit);
typedef void (*on_NtTestAlert_enter_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtImpersonateAnonymousToken_return_t)(CPUState* env,target_ulong pc,uint32_t Thread);
typedef void (*on_NtCreatePort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ObjectAttributes,uint32_t MaxConnectionInfoLength,uint32_t MaxMessageLength,uint32_t MaxPoolUsage);
typedef void (*on_NtDisplayString_enter_t)(CPUState* env,target_ulong pc,uint32_t DisplayString);
typedef void (*on_NtSetInformationObject_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectHandle,uint32_t ObjectInformationClass,uint32_t ObjectInformation,uint32_t Length);
typedef void (*on_NtLoadKey2_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes,uint32_t FileObjectAttributes,uint32_t Flags);
typedef void (*on_NtUnloadKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes);
typedef void (*on_NtQueryDebugFilterState_return_t)(CPUState* env,target_ulong pc,uint32_t ComponentId,uint32_t Level);
typedef void (*on_unknown_sys_windows7_x86_return_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_NtFlushInstructionCache_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToFlush);
typedef void (*on_NtCreateMutant_enter_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t InitialOwner);
typedef void (*on_NtUnloadDriver_return_t)(CPUState* env,target_ulong pc,uint32_t DriverServiceName);
typedef void (*on_NtWaitForMultipleObjects_return_t)(CPUState* env,target_ulong pc,uint32_t Count,uint32_t Object,uint32_t WaitType,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtAccessCheckAndAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ObjectTypeName,uint32_t ObjectName,uint32_t SecurityDescriptor,uint32_t DesiredAccess,uint32_t GenericMapping,uint32_t ObjectCreation,uint32_t GrantedAccess,uint32_t AccessStatus,uint32_t GenerateOnClose);
typedef void (*on_NtQueryVolumeInformationFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FsInformation,uint32_t Length,uint32_t FsInformationClass);
typedef void (*on_NtQueryPortInformationProcess_return_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtQueryVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t Address,uint32_t VirtualMemoryInformationClass,uint32_t VirtualMemoryInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtReadFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtOpenProcessTokenEx_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t HandleAttributes,uint32_t TokenHandle);
typedef void (*on_NtOpenMutant_enter_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetSecurityObject_enter_t)(CPUState* env,target_ulong pc,uint32_t Handle,uint32_t SecurityInformation,uint32_t SecurityDescriptor);
typedef void (*on_NtCreateProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ParentProcess,uint32_t InheritObjectTable,uint32_t SectionHandle,uint32_t DebugPort,uint32_t ExceptionPort);
typedef void (*on_NtExtendSection_enter_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t NewMaximumSize);
typedef void (*on_NtQueryKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtCreateThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ProcessHandle,uint32_t ClientId,uint32_t ThreadContext,uint32_t UserStack,uint32_t CreateSuspended);
typedef void (*on_NtCallbackReturn_return_t)(CPUState* env,target_ulong pc,uint32_t Result,uint32_t ResultLength,uint32_t Status);
typedef void (*on_NtFlushWriteBuffer_enter_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtShutdownSystem_return_t)(CPUState* env,target_ulong pc,uint32_t Action);
typedef void (*on_NtDebugActiveProcess_return_t)(CPUState* env,target_ulong pc,uint32_t Process,uint32_t DebugObject);
typedef void (*on_NtConnectPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortName,uint32_t SecurityQos,uint32_t ClientView,uint32_t ServerView,uint32_t MaxMessageLength,uint32_t ConnectionInformation,uint32_t ConnectionInformationLength);
typedef void (*on_NtImpersonateClientOfPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ClientMessage);
typedef void (*on_NtCreateWaitablePort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ObjectAttributes,uint32_t MaxConnectInfoLength,uint32_t MaxDataLength,uint32_t NPMessageQueueSize);
typedef void (*on_NtNotifyChangeKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t CompletionFilter,uint32_t Asynchroneous,uint32_t ChangeBuffer,uint32_t Length,uint32_t WatchSubtree);
typedef void (*on_NtProtectVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,target_ulong NumberOfBytesToProtect,uint32_t NewAccessProtection,uint32_t OldAccessProtection);
typedef void (*on_NtDeleteObjectAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t GenerateOnClose);
typedef void (*on_NtAllocateUserPhysicalPages_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtFlushKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtResetEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t NumberOfWaitingThreads);
typedef void (*on_NtSetSystemEnvironmentValue_enter_t)(CPUState* env,target_ulong pc,uint32_t VariableName,uint32_t Value);
typedef void (*on_NtQueryMultipleValueKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueList,uint32_t NumberOfValues,uint32_t Buffer,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtRenameKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ReplacementName);
typedef void (*on_NtCancelTimer_return_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t CurrentState);
typedef void (*on_NtTerminateJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t ExitStatus);
typedef void (*on_NtSetDefaultUILanguage_return_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtAllocateUuids_return_t)(CPUState* env,target_ulong pc,uint32_t Time,uint32_t Range,uint32_t Sequence,uint32_t Seed);
typedef void (*on_NtSetVolumeInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FsInformation,uint32_t Length,uint32_t FsInformationClass);
typedef void (*on_NtRaiseException_enter_t)(CPUState* env,target_ulong pc,uint32_t ExceptionRecord,uint32_t Context,uint32_t SearchFrames);
typedef void (*on_NtSetInformationDebugObject_enter_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t InformationClass,uint32_t Information,uint32_t InformationLength,uint32_t ReturnLength);
typedef void (*on_NtCreateSemaphore_enter_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,int32_t InitialCount,int32_t MaximumCount);
typedef void (*on_NtSetInformationToken_return_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t TokenInformationClass,uint32_t TokenInformation,uint32_t TokenInformationLength);
typedef void (*on_NtResumeProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle);
typedef void (*on_NtQueryInformationJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t JobInformationClass,uint32_t JobInformation,uint32_t JobInformationLength,uint32_t ReturnLength);
typedef void (*on_NtCompressKey_enter_t)(CPUState* env,target_ulong pc,uint32_t Key);
typedef void (*on_NtGetWriteWatch_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t Flags,uint32_t BaseAddress,uint32_t RegionSize,target_ulong UserAddressArray,uint32_t EntriesInUserAddressArray,uint32_t Granularity);
typedef void (*on_NtOpenFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t ShareAccess,uint32_t OpenOptions);
typedef void (*on_NtOpenKeyedEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateSection_enter_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t MaximumSize,uint32_t SectionPageProtection,uint32_t AllocationAttributes,uint32_t FileHandle);
typedef void (*on_NtCreateToken_enter_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TokenType,uint32_t AuthenticationId,uint32_t ExpirationTime,uint32_t TokenUser,uint32_t TokenGroups,uint32_t TokenPrivileges,uint32_t TokenOwner,uint32_t TokenPrimaryGroup,uint32_t TokenDefaultDacl,uint32_t TokenSource);
typedef void (*on_NtResetWriteWatch_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t RegionSize);
typedef void (*on_NtVdmControl_return_t)(CPUState* env,target_ulong pc,uint32_t ControlCode,uint32_t ControlData);
typedef void (*on_NtLoadKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes,uint32_t FileObjectAttributes);
typedef void (*on_NtQueryDefaultUILanguage_enter_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtImpersonateAnonymousToken_enter_t)(CPUState* env,target_ulong pc,uint32_t Thread);
typedef void (*on_NtSetLowWaitHighEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPair);
typedef void (*on_NtSetIoCompletion_enter_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionPortHandle,uint32_t CompletionKey,uint32_t CompletionContext,uint32_t CompletionStatus,uint32_t CompletionInformation);
typedef void (*on_NtWaitHighEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtQueryTimer_enter_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t TimerInformationClass,uint32_t TimerInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtPowerInformation_enter_t)(CPUState* env,target_ulong pc,uint32_t PowerInformationLevel,uint32_t InputBuffer,uint32_t InputBufferLength,uint32_t OutputBuffer,uint32_t OutputBufferLength);
typedef void (*on_NtQuerySystemEnvironmentValueEx_enter_t)(CPUState* env,target_ulong pc,uint32_t VariableName,uint32_t VendorGuid,uint32_t Value,uint32_t ReturnLength,uint32_t Attributes);
typedef void (*on_NtOpenFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t ShareAccess,uint32_t OpenOptions);
typedef void (*on_NtUnloadDriver_enter_t)(CPUState* env,target_ulong pc,uint32_t DriverServiceName);
typedef void (*on_NtClearEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle);
typedef void (*on_NtQuerySection_return_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t SectionInformationClass,uint32_t SectionInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtDisplayString_return_t)(CPUState* env,target_ulong pc,uint32_t DisplayString);
typedef void (*on_NtPrivilegeObjectAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t Privileges,uint32_t AccessGranted);
typedef void (*on_NtFlushWriteBuffer_return_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtOpenSection_return_t)(CPUState* env,target_ulong pc,uint32_t SectionHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtWaitForDebugEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t Alertable,uint32_t Timeout,uint32_t StateChange);
typedef void (*on_NtFsControlFile_return_t)(CPUState* env,target_ulong pc,uint32_t DeviceHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t IoControlCode,uint32_t InputBuffer,uint32_t InputBufferSize,uint32_t OutputBuffer,uint32_t OutputBufferSize);
typedef void (*on_NtSetSystemTime_enter_t)(CPUState* env,target_ulong pc,uint32_t SystemTime,uint32_t NewSystemTime);
typedef void (*on_NtQueryInformationProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ProcessInformationClass,uint32_t ProcessInformation,uint32_t ProcessInformationLength,uint32_t ReturnLength);
typedef void (*on_NtCreateSymbolicLinkObject_enter_t)(CPUState* env,target_ulong pc,uint32_t SymbolicLinkHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t Name);
typedef void (*on_NtOpenIoCompletion_return_t)(CPUState* env,target_ulong pc,uint32_t CompetionPort,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetSystemEnvironmentValue_return_t)(CPUState* env,target_ulong pc,uint32_t VariableName,uint32_t Value);
typedef void (*on_NtSecureConnectPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortName,uint32_t SecurityQos,uint32_t ClientView,uint32_t Sid,uint32_t ServerView,uint32_t MaxMessageLength,uint32_t ConnectionInformation,uint32_t ConnectionInformationLength);
typedef void (*on_NtImpersonateClientOfPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ClientMessage);
typedef void (*on_NtClose_enter_t)(CPUState* env,target_ulong pc,uint32_t Handle);
typedef void (*on_NtSetInformationObject_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectHandle,uint32_t ObjectInformationClass,uint32_t ObjectInformation,uint32_t Length);
typedef void (*on_NtCompactKeys_return_t)(CPUState* env,target_ulong pc,uint32_t Count,uint32_t KeyArray);
typedef void (*on_NtEnumerateSystemEnvironmentValuesEx_enter_t)(CPUState* env,target_ulong pc,uint32_t InformationClass,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtCallbackReturn_enter_t)(CPUState* env,target_ulong pc,uint32_t Result,uint32_t ResultLength,uint32_t Status);
typedef void (*on_NtReadRequestData_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t Message,uint32_t Index,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnLength);
typedef void (*on_NtOpenKeyEx_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t OpenOptions);
typedef void (*on_NtSaveKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle);
typedef void (*on_NtAllocateLocallyUniqueId_enter_t)(CPUState* env,target_ulong pc,target_ulong LocallyUniqueId);
typedef void (*on_NtMapUserPhysicalPages_enter_t)(CPUState* env,target_ulong pc,target_ulong VirtualAddresses,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtOpenKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtQuerySemaphore_enter_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t SemaphoreInformationClass,uint32_t SemaphoreInformation,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtSetInformationThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadInformationClass,uint32_t ThreadInformation,uint32_t ThreadInformationLength);
typedef void (*on_NtInitiatePowerAction_return_t)(CPUState* env,target_ulong pc,uint32_t SystemAction,uint32_t MinSystemState,uint32_t Flags,uint32_t Asynchronous);
typedef void (*on_NtQueryDebugFilterState_enter_t)(CPUState* env,target_ulong pc,uint32_t ComponentId,uint32_t Level);
typedef void (*on_NtLoadKey2_return_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes,uint32_t FileObjectAttributes,uint32_t Flags);
typedef void (*on_NtQueryFullAttributesFile_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t FileInformation);
typedef void (*on_NtTerminateProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ExitStatus);
typedef void (*on_NtEnumerateValueKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Index,uint32_t KeyValueInformationClass,uint32_t KeyValueInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtSetQuotaInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtSetEaFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t EaBuffer,uint32_t EaBufferSize);
typedef void (*on_NtMakePermanentObject_enter_t)(CPUState* env,target_ulong pc,uint32_t Object);
typedef void (*on_NtCreateKeyedEvent_return_t)(CPUState* env,target_ulong pc,uint32_t KeyedEventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t Flags);
typedef void (*on_NtCreateProfile_return_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle,uint32_t ProcessHandle,uint32_t ImageBase,uint32_t ImageSize,uint32_t Granularity,uint32_t Buffer,uint32_t ProfilingSize,uint32_t Source,uint32_t ProcessorMask);
typedef void (*on_NtOpenObjectAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ObjectTypeName,uint32_t ObjectName,uint32_t SecurityDescriptor,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t GrantedAccess,uint32_t Privileges,uint32_t ObjectCreation,uint32_t AccessGranted,uint32_t GenerateOnClose);
typedef void (*on_NtQueryDefaultUILanguage_return_t)(CPUState* env,target_ulong pc,uint32_t LanguageId);
typedef void (*on_NtSetValueKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName,uint32_t TitleIndex,uint32_t Type,uint32_t Data,uint32_t DataSize);
typedef void (*on_NtSetLowEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPair);
typedef void (*on_NtLoadDriver_return_t)(CPUState* env,target_ulong pc,uint32_t DriverServiceName);
typedef void (*on_NtTraceEvent_return_t)(CPUState* env,target_ulong pc,uint32_t TraceHandle,uint32_t Flags,uint32_t TraceHeaderLength,uint32_t TraceHeader);
typedef void (*on_NtSaveMergedKeys_enter_t)(CPUState* env,target_ulong pc,uint32_t HighPrecedenceKeyHandle,uint32_t LowPrecedenceKeyHandle,uint32_t FileHandle);
typedef void (*on_NtCreateKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TitleIndex,uint32_t Class,uint32_t CreateOptions,uint32_t Disposition);
typedef void (*on_NtSetLdtEntries_enter_t)(CPUState* env,target_ulong pc,uint32_t Selector1,uint32_t LdtEntry1,uint32_t Selector2,uint32_t LdtEntry2);
typedef void (*on_NtStartProfile_enter_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle);
typedef void (*on_NtQueueApcThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ApcRoutine,uint32_t NormalContext,uint32_t SystemArgument1,uint32_t SystemArgument2);
typedef void (*on_NtWaitHighEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtSetSystemPowerState_enter_t)(CPUState* env,target_ulong pc,uint32_t SystemAction,uint32_t MinSystemState,uint32_t Flags);
typedef void (*on_NtQuerySecurityObject_return_t)(CPUState* env,target_ulong pc,uint32_t Handle,uint32_t SecurityInformation,uint32_t SecurityDescriptor,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtAdjustGroupsToken_enter_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t ResetToDefault,uint32_t NewState,uint32_t BufferLength,uint32_t PreviousState,uint32_t ReturnLength);
typedef void (*on_NtCreateMailslotFile_enter_t)(CPUState* env,target_ulong pc,uint32_t MailSlotFileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t FileAttributes,uint32_t ShareAccess,uint32_t MaxMessageSize,uint32_t TimeOut);
typedef void (*on_NtClose_return_t)(CPUState* env,target_ulong pc,uint32_t Handle);
typedef void (*on_NtOpenEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t AllocationSize,uint32_t FileAttributes,uint32_t ShareAccess,uint32_t CreateDisposition,uint32_t CreateOptions,uint32_t EaBuffer,uint32_t EaLength);
typedef void (*on_NtEnumerateKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Index,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtSetInformationJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t JobInformationClass,uint32_t JobInformation,uint32_t JobInformationLength);
typedef void (*on_NtConnectPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortName,uint32_t SecurityQos,uint32_t ClientView,uint32_t ServerView,uint32_t MaxMessageLength,uint32_t ConnectionInformation,uint32_t ConnectionInformationLength);
typedef void (*on_NtTerminateThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ExitStatus);
typedef void (*on_NtAdjustPrivilegesToken_enter_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t DisableAllPrivileges,uint32_t NewState,uint32_t BufferLength,uint32_t PreviousState,uint32_t ReturnLength);
typedef void (*on_NtStartProfile_return_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle);
typedef void (*on_NtSaveKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle);
typedef void (*on_NtMapUserPhysicalPagesScatter_enter_t)(CPUState* env,target_ulong pc,target_ulong VirtualAddresses,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtDuplicateToken_return_t)(CPUState* env,target_ulong pc,uint32_t ExistingTokenHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t EffectiveOnly,uint32_t TokenType,uint32_t NewTokenHandle);
typedef void (*on_NtSetContextThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t Context);
typedef void (*on_NtResumeThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t SuspendCount);
typedef void (*on_NtNotifyChangeMultipleKeys_return_t)(CPUState* env,target_ulong pc,uint32_t MasterKeyHandle,uint32_t Count,uint32_t SlaveObjects,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t CompletionFilter,uint32_t WatchTree,uint32_t Buffer,uint32_t Length,uint32_t Asynchronous);
typedef void (*on_NtQueryOpenSubKeys_return_t)(CPUState* env,target_ulong pc,uint32_t TargetKey,uint32_t HandleCount);
typedef void (*on_NtAreMappedFilesTheSame_return_t)(CPUState* env,target_ulong pc,uint32_t File1MappedAsAnImage,uint32_t File2MappedAsFile);
typedef void (*on_NtDeleteValueKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName);
typedef void (*on_NtAlertResumeThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t SuspendCount);
typedef void (*on_NtRemoveProcessDebug_return_t)(CPUState* env,target_ulong pc,uint32_t Process,uint32_t DebugObject);
typedef void (*on_NtGetPlugPlayEvent_return_t)(CPUState* env,target_ulong pc,uint32_t Reserved1,uint32_t Reserved2,uint32_t Buffer,uint32_t BufferSize);
typedef void (*on_NtQueryEaFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ReturnSingleEntry,uint32_t EaList,uint32_t EaListLength,uint32_t EaIndex,uint32_t RestartScan);
typedef void (*on_NtResumeThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t SuspendCount);
typedef void (*on_NtCloseObjectAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t GenerateOnClose);
typedef void (*on_NtSaveKeyEx_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle,uint32_t Flags);
typedef void (*on_NtCreateJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtOpenEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetInformationJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t JobInformationClass,uint32_t JobInformation,uint32_t JobInformationLength);
typedef void (*on_NtRemoveIoCompletion_return_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,target_ulong CompletionKey,target_ulong CompletionContext,uint32_t IoStatusBlock,uint32_t Timeout);
typedef void (*on_NtWaitLowEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtQueryInformationThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadInformationClass,uint32_t ThreadInformation,uint32_t ThreadInformationLength,uint32_t ReturnLength);
typedef void (*on_NtReadFileScatter_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t UserIoStatusBlock,uint32_t BufferDescription,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtRegisterThreadTerminatePort_return_t)(CPUState* env,target_ulong pc,uint32_t TerminationPort);
typedef void (*on_NtOpenThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ClientId);
typedef void (*on_NtSetHighWaitLowEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtSetValueKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName,uint32_t TitleIndex,uint32_t Type,uint32_t Data,uint32_t DataSize);
typedef void (*on_NtSignalAndWaitForSingleObject_return_t)(CPUState* env,target_ulong pc,uint32_t SignalObject,uint32_t WaitObject,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtQueryFullAttributesFile_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t FileInformation);
typedef void (*on_NtQueryInformationToken_return_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t TokenInformationClass,uint32_t TokenInformation,uint32_t TokenInformationLength,uint32_t ReturnLength);
typedef void (*on_NtSetHighEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtCreateEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t EventType,uint32_t InitialState);
typedef void (*on_NtOpenSymbolicLinkObject_enter_t)(CPUState* env,target_ulong pc,uint32_t SymbolicLinkHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateNamedPipeFile_return_t)(CPUState* env,target_ulong pc,uint32_t NamedPipeFileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t ShareAccess,uint32_t CreateDisposition,uint32_t CreateOptions,uint32_t WriteModeMessage,uint32_t ReadModeMessage,uint32_t NonBlocking,uint32_t MaxInstances,uint32_t InBufferSize,uint32_t OutBufferSize,uint32_t DefaultTimeOut);
typedef void (*on_NtAccessCheckByType_enter_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t PrincipalSelfSid,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t ObjectTypeList,uint32_t ObjectTypeLength,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t PrivilegeSetLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_NtTerminateThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ExitStatus);
typedef void (*on_NtListenPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ConnectionRequest);
typedef void (*on_NtSetInformationKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t KeyInformationLength);
typedef void (*on_NtCancelTimer_enter_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t CurrentState);
typedef void (*on_NtFreeUserPhysicalPages_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtCreatePort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ObjectAttributes,uint32_t MaxConnectionInfoLength,uint32_t MaxMessageLength,uint32_t MaxPoolUsage);
typedef void (*on_NtCreateToken_return_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TokenType,uint32_t AuthenticationId,uint32_t ExpirationTime,uint32_t TokenUser,uint32_t TokenGroups,uint32_t TokenPrivileges,uint32_t TokenOwner,uint32_t TokenPrimaryGroup,uint32_t TokenDefaultDacl,uint32_t TokenSource);
typedef void (*on_NtTranslateFilePath_enter_t)(CPUState* env,target_ulong pc,uint32_t InputFilePath,uint32_t OutputType,uint32_t OutputFilePath,uint32_t OutputFilePathLength);
typedef void (*on_NtLoadKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes,uint32_t FileObjectAttributes);
typedef void (*on_NtCreateProfile_enter_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle,uint32_t ProcessHandle,uint32_t ImageBase,uint32_t ImageSize,uint32_t Granularity,uint32_t Buffer,uint32_t ProfilingSize,uint32_t Source,uint32_t ProcessorMask);
typedef void (*on_NtUnlockFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t ByteOffset,uint32_t Lenght,uint32_t Key);
typedef void (*on_NtEnumerateValueKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Index,uint32_t KeyValueInformationClass,uint32_t KeyValueInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtLockProductActivationKeys_enter_t)(CPUState* env,target_ulong pc,uint32_t pPrivateVer,uint32_t pSafeMode);
typedef void (*on_NtCancelIoFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock);
typedef void (*on_NtCreateKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TitleIndex,uint32_t Class,uint32_t CreateOptions,uint32_t Disposition);
typedef void (*on_NtQuerySecurityObject_enter_t)(CPUState* env,target_ulong pc,uint32_t Handle,uint32_t SecurityInformation,uint32_t SecurityDescriptor,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtQueryInformationAtom_enter_t)(CPUState* env,target_ulong pc,uint32_t Atom,uint32_t AtomInformationClass,uint32_t AtomInformation,uint32_t AtomInformationLength,uint32_t ReturnLength);
typedef void (*on_NtQueryDefaultLocale_return_t)(CPUState* env,target_ulong pc,uint32_t UserProfile,uint32_t DefaultLocaleId);
typedef void (*on_NtVdmControl_enter_t)(CPUState* env,target_ulong pc,uint32_t ControlCode,uint32_t ControlData);
typedef void (*on_NtTranslateFilePath_return_t)(CPUState* env,target_ulong pc,uint32_t InputFilePath,uint32_t OutputType,uint32_t OutputFilePath,uint32_t OutputFilePathLength);
typedef void (*on_NtQueryObject_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectHandle,uint32_t ObjectInformationClass,uint32_t ObjectInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtRequestPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcMessage);
typedef void (*on_NtSetTimerResolution_enter_t)(CPUState* env,target_ulong pc,uint32_t RequestedResolution,uint32_t SetOrUnset,uint32_t ActualResolution);
typedef void (*on_NtCompleteConnectPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle);
typedef void (*on_NtReplaceKey_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t Key,uint32_t ReplacedObjectAttributes);
typedef void (*on_NtStopProfile_enter_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle);
typedef void (*on_NtSystemDebugControl_enter_t)(CPUState* env,target_ulong pc,uint32_t ControlCode,uint32_t InputBuffer,uint32_t InputBufferLength,uint32_t OutputBuffer,uint32_t OutputBufferLength,uint32_t ReturnLength);
typedef void (*on_NtRequestPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcMessage);
typedef void (*on_NtUnlockFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t ByteOffset,uint32_t Lenght,uint32_t Key);
typedef void (*on_NtEnumerateBootEntries_enter_t)(CPUState* env,target_ulong pc,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtQueryVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t Address,uint32_t VirtualMemoryInformationClass,uint32_t VirtualMemoryInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtDelayExecution_enter_t)(CPUState* env,target_ulong pc,uint32_t Alertable,target_ulong Interval);
typedef void (*on_NtWaitForDebugEvent_return_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t Alertable,uint32_t Timeout,uint32_t StateChange);
typedef void (*on_NtSetTimer_return_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DueTime,uint32_t TimerApcRoutine,uint32_t TimerContext,uint32_t WakeTimer,int32_t Period,uint32_t PreviousState);
typedef void (*on_NtCreateProcessEx_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ParentProcess,uint32_t Flags,uint32_t SectionHandle,uint32_t DebugPort,uint32_t ExceptionPort,uint32_t InJob);
typedef void (*on_NtDeleteKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtInitializeRegistry_return_t)(CPUState* env,target_ulong pc,uint32_t Flag);
typedef void (*on_NtSetUuidSeed_return_t)(CPUState* env,target_ulong pc,uint32_t UuidSeed);
typedef void (*on_NtOpenTimer_enter_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtQueryTimerResolution_return_t)(CPUState* env,target_ulong pc,uint32_t MinimumResolution,uint32_t MaximumResolution,uint32_t ActualResolution);
typedef void (*on_NtCompactKeys_enter_t)(CPUState* env,target_ulong pc,uint32_t Count,uint32_t KeyArray);
typedef void (*on_NtQueryDirectoryFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass,uint32_t ReturnSingleEntry,uint32_t FileName,uint32_t RestartScan);
typedef void (*on_NtDebugContinue_return_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t AppClientId,uint32_t ContinueStatus);
typedef void (*on_NtOpenThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ClientId);
typedef void (*on_NtSetLdtEntries_return_t)(CPUState* env,target_ulong pc,uint32_t Selector1,uint32_t LdtEntry1,uint32_t Selector2,uint32_t LdtEntry2);
typedef void (*on_NtQueryObject_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectHandle,uint32_t ObjectInformationClass,uint32_t ObjectInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtAlertThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle);
typedef void (*on_NtLockProductActivationKeys_return_t)(CPUState* env,target_ulong pc,uint32_t pPrivateVer,uint32_t pSafeMode);
typedef void (*on_NtQuerySystemInformation_enter_t)(CPUState* env,target_ulong pc,uint32_t SystemInformationClass,uint32_t SystemInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtOpenProcessToken_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t TokenHandle);
typedef void (*on_NtDebugContinue_enter_t)(CPUState* env,target_ulong pc,uint32_t DebugObject,uint32_t AppClientId,uint32_t ContinueStatus);
typedef void (*on_NtDebugActiveProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t Process,uint32_t DebugObject);
typedef void (*on_NtCreateEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtShutdownSystem_enter_t)(CPUState* env,target_ulong pc,uint32_t Action);
typedef void (*on_NtFreeVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t RegionSize,uint32_t FreeType);
typedef void (*on_NtSaveKeyEx_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t FileHandle,uint32_t Flags);
typedef void (*on_NtOpenDirectoryObject_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtSetHighEventPair_return_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtContinue_enter_t)(CPUState* env,target_ulong pc,uint32_t Context,uint32_t TestAlert);
typedef void (*on_NtSuspendProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle);
typedef void (*on_NtQueryDirectoryObject_enter_t)(CPUState* env,target_ulong pc,uint32_t DirectoryHandle,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnSingleEntry,uint32_t RestartScan,uint32_t Context,uint32_t ReturnLength);
typedef void (*on_NtSetTimerResolution_return_t)(CPUState* env,target_ulong pc,uint32_t RequestedResolution,uint32_t SetOrUnset,uint32_t ActualResolution);
typedef void (*on_NtSetInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass);
typedef void (*on_NtSetDefaultLocale_return_t)(CPUState* env,target_ulong pc,uint32_t UserProfile,uint32_t DefaultLocaleId);
typedef void (*on_NtSetDebugFilterState_enter_t)(CPUState* env,target_ulong pc,uint32_t ComponentId,uint32_t Level,uint32_t State);
typedef void (*on_unknown_sys_windows7_x86_enter_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_NtQueryInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FileInformation,uint32_t Length,uint32_t FileInformationClass);
typedef void (*on_NtAccessCheckByTypeResultList_return_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t PrincipalSelfSid,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t ObjectTypeList,uint32_t ObjectTypeLength,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t PrivilegeSetLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_NtDeleteKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtGetContextThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t Context);
typedef void (*on_NtCreateWaitablePort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ObjectAttributes,uint32_t MaxConnectInfoLength,uint32_t MaxDataLength,uint32_t NPMessageQueueSize);
typedef void (*on_NtLoadDriver_enter_t)(CPUState* env,target_ulong pc,uint32_t DriverServiceName);
typedef void (*on_NtLockRegistryKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtQueryPerformanceCounter_return_t)(CPUState* env,target_ulong pc,uint32_t Counter,uint32_t Frequency);
typedef void (*on_NtSetDefaultHardErrorPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle);
typedef void (*on_NtOpenMutant_return_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtOpenThreadToken_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t OpenAsSelf,uint32_t TokenHandle);
typedef void (*on_NtQueryValueKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName,uint32_t KeyValueInformationClass,uint32_t KeyValueInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtReadFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtInitializeRegistry_enter_t)(CPUState* env,target_ulong pc,uint32_t Flag);
typedef void (*on_NtQuerySystemEnvironmentValue_enter_t)(CPUState* env,target_ulong pc,uint32_t Name,uint32_t Value,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtFlushVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t RegionSize,uint32_t IoStatus);
typedef void (*on_NtOpenJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCreateMailslotFile_return_t)(CPUState* env,target_ulong pc,uint32_t MailSlotFileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t FileAttributes,uint32_t ShareAccess,uint32_t MaxMessageSize,uint32_t TimeOut);
typedef void (*on_NtQueryTimerResolution_enter_t)(CPUState* env,target_ulong pc,uint32_t MinimumResolution,uint32_t MaximumResolution,uint32_t ActualResolution);
typedef void (*on_NtCreateTimer_return_t)(CPUState* env,target_ulong pc,uint32_t TimerHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t TimerType);
typedef void (*on_NtTerminateProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ExitStatus);
typedef void (*on_NtRegisterThreadTerminatePort_enter_t)(CPUState* env,target_ulong pc,uint32_t TerminationPort);
typedef void (*on_NtPulseEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t PulseCount);
typedef void (*on_NtSetDebugFilterState_return_t)(CPUState* env,target_ulong pc,uint32_t ComponentId,uint32_t Level,uint32_t State);
typedef void (*on_NtQuerySystemTime_enter_t)(CPUState* env,target_ulong pc,uint32_t CurrentTime);
typedef void (*on_NtQueryAttributesFile_enter_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t FileInformation);
typedef void (*on_NtYieldExecution_enter_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtIsProcessInJob_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t JobHandle);
typedef void (*on_NtReplyWaitReplyPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t ReplyMessage);
typedef void (*on_NtQueryMultipleValueKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueList,uint32_t NumberOfValues,uint32_t Buffer,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtFreeVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t RegionSize,uint32_t FreeType);
typedef void (*on_NtReplyPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcReply);
typedef void (*on_NtSignalAndWaitForSingleObject_enter_t)(CPUState* env,target_ulong pc,uint32_t SignalObject,uint32_t WaitObject,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtQueueApcThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ApcRoutine,uint32_t NormalContext,uint32_t SystemArgument1,uint32_t SystemArgument2);
typedef void (*on_NtAccessCheck_return_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t ReturnLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_NtDelayExecution_return_t)(CPUState* env,target_ulong pc,uint32_t Alertable,target_ulong Interval);
typedef void (*on_NtGetWriteWatch_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t Flags,uint32_t BaseAddress,uint32_t RegionSize,target_ulong UserAddressArray,uint32_t EntriesInUserAddressArray,uint32_t Granularity);
typedef void (*on_NtQueryInformationPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortInformationClass,uint32_t PortInformation,uint32_t PortInformationLength,uint32_t ReturnLength);
typedef void (*on_NtFlushVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t RegionSize,uint32_t IoStatus);
typedef void (*on_NtOpenJobObject_enter_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtUnloadKeyEx_return_t)(CPUState* env,target_ulong pc,uint32_t TargetKey,uint32_t Event);
typedef void (*on_NtNotifyChangeDirectoryFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t BufferSize,uint32_t CompletionFilter,uint32_t WatchTree);
typedef void (*on_NtLockRegistryKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtQueryInformationToken_enter_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t TokenInformationClass,uint32_t TokenInformation,uint32_t TokenInformationLength,uint32_t ReturnLength);
typedef void (*on_NtOpenEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCloseObjectAuditAlarm_return_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t GenerateOnClose);
typedef void (*on_NtRemoveIoCompletion_enter_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,target_ulong CompletionKey,target_ulong CompletionContext,uint32_t IoStatusBlock,uint32_t Timeout);
typedef void (*on_NtCreateNamedPipeFile_enter_t)(CPUState* env,target_ulong pc,uint32_t NamedPipeFileHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t IoStatusBlock,uint32_t ShareAccess,uint32_t CreateDisposition,uint32_t CreateOptions,uint32_t WriteModeMessage,uint32_t ReadModeMessage,uint32_t NonBlocking,uint32_t MaxInstances,uint32_t InBufferSize,uint32_t OutBufferSize,uint32_t DefaultTimeOut);
typedef void (*on_NtNotifyChangeMultipleKeys_enter_t)(CPUState* env,target_ulong pc,uint32_t MasterKeyHandle,uint32_t Count,uint32_t SlaveObjects,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t CompletionFilter,uint32_t WatchTree,uint32_t Buffer,uint32_t Length,uint32_t Asynchronous);
typedef void (*on_NtRequestWaitReplyPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcReply,uint32_t LpcRequest);
typedef void (*on_NtQueryEaFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ReturnSingleEntry,uint32_t EaList,uint32_t EaListLength,uint32_t EaIndex,uint32_t RestartScan);
typedef void (*on_NtDuplicateToken_enter_t)(CPUState* env,target_ulong pc,uint32_t ExistingTokenHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t EffectiveOnly,uint32_t TokenType,uint32_t NewTokenHandle);
typedef void (*on_NtWriteRequestData_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t Message,uint32_t Index,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnLength);
typedef void (*on_NtOpenProcessToken_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t TokenHandle);
typedef void (*on_NtDeleteAtom_return_t)(CPUState* env,target_ulong pc,uint32_t Atom);
typedef void (*on_NtQuerySystemEnvironmentValueEx_return_t)(CPUState* env,target_ulong pc,uint32_t VariableName,uint32_t VendorGuid,uint32_t Value,uint32_t ReturnLength,uint32_t Attributes);
typedef void (*on_NtCancelIoFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock);
typedef void (*on_NtDeleteValueKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName);
typedef void (*on_NtSetInformationProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ProcessInformationClass,uint32_t ProcessInformation,uint32_t ProcessInformationLength);
typedef void (*on_NtCreateDirectoryObject_enter_t)(CPUState* env,target_ulong pc,uint32_t DirectoryHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtLockFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t ByteOffset,uint32_t Length,uint32_t Key,uint32_t FailImmediatedly,uint32_t ExclusiveLock);
typedef void (*on_NtGetContextThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t Context);
typedef void (*on_NtAcceptConnectPort_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t PortContext,uint32_t ConnectionRequest,uint32_t AcceptConnection,uint32_t ServerView,uint32_t ClientView);
typedef void (*on_NtDeviceIoControlFile_return_t)(CPUState* env,target_ulong pc,uint32_t DeviceHandle,uint32_t Event,uint32_t UserApcRoutine,uint32_t UserApcContext,uint32_t IoStatusBlock,uint32_t IoControlCode,uint32_t InputBuffer,uint32_t InputBufferSize,uint32_t OutputBuffer,uint32_t OutputBufferSize);
typedef void (*on_NtAccessCheckAndAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ObjectTypeName,uint32_t ObjectName,uint32_t SecurityDescriptor,uint32_t DesiredAccess,uint32_t GenericMapping,uint32_t ObjectCreation,uint32_t GrantedAccess,uint32_t AccessStatus,uint32_t GenerateOnClose);
typedef void (*on_NtSetEventBoostPriority_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle);
typedef void (*on_NtResetWriteWatch_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t RegionSize);
typedef void (*on_NtGetPlugPlayEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t Reserved1,uint32_t Reserved2,uint32_t Buffer,uint32_t BufferSize);
typedef void (*on_NtCreateSymbolicLinkObject_return_t)(CPUState* env,target_ulong pc,uint32_t SymbolicLinkHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t Name);
typedef void (*on_NtQueryPerformanceCounter_enter_t)(CPUState* env,target_ulong pc,uint32_t Counter,uint32_t Frequency);
typedef void (*on_NtLockVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToLock,uint32_t NumberOfBytesLocked);
typedef void (*on_NtAddAtom_return_t)(CPUState* env,target_ulong pc,uint32_t AtomName,uint32_t AtomNameLength,uint32_t Atom);
typedef void (*on_NtQueryInformationProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ProcessInformationClass,uint32_t ProcessInformation,uint32_t ProcessInformationLength,uint32_t ReturnLength);
typedef void (*on_NtStopProfile_return_t)(CPUState* env,target_ulong pc,uint32_t ProfileHandle);
typedef void (*on_NtSuspendThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t PreviousSuspendCount);
typedef void (*on_NtWriteFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtQueryEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t EventInformationClass,uint32_t EventInformation,uint32_t EventInformationLength,uint32_t ReturnLength);
typedef void (*on_NtWriteFileGather_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t BufferDescription,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtSetInformationProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t ProcessInformationClass,uint32_t ProcessInformation,uint32_t ProcessInformationLength);
typedef void (*on_NtSetUuidSeed_enter_t)(CPUState* env,target_ulong pc,uint32_t UuidSeed);
typedef void (*on_NtCompleteConnectPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle);
typedef void (*on_NtAccessCheckByType_return_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t PrincipalSelfSid,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t ObjectTypeList,uint32_t ObjectTypeLength,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t PrivilegeSetLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_NtAdjustPrivilegesToken_return_t)(CPUState* env,target_ulong pc,uint32_t TokenHandle,uint32_t DisableAllPrivileges,uint32_t NewState,uint32_t BufferLength,uint32_t PreviousState,uint32_t ReturnLength);
typedef void (*on_NtSetInformationThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t ThreadInformationClass,uint32_t ThreadInformation,uint32_t ThreadInformationLength);
typedef void (*on_NtWaitForSingleObject_enter_t)(CPUState* env,target_ulong pc,uint32_t Object,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtOpenThreadTokenEx_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t OpenAsSelf,uint32_t HandleAttributes,uint32_t TokenHandle);
typedef void (*on_NtPrivilegeObjectAuditAlarm_enter_t)(CPUState* env,target_ulong pc,uint32_t SubsystemName,uint32_t HandleId,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t Privileges,uint32_t AccessGranted);
typedef void (*on_NtQuerySemaphore_return_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t SemaphoreInformationClass,uint32_t SemaphoreInformation,uint32_t Length,uint32_t ReturnLength);
typedef void (*on_NtProtectVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,target_ulong NumberOfBytesToProtect,uint32_t NewAccessProtection,uint32_t OldAccessProtection);
typedef void (*on_NtPrivilegeCheck_enter_t)(CPUState* env,target_ulong pc,uint32_t ClientToken,uint32_t RequiredPrivileges,uint32_t Result);
typedef void (*on_NtRaiseException_return_t)(CPUState* env,target_ulong pc,uint32_t ExceptionRecord,uint32_t Context,uint32_t SearchFrames);
typedef void (*on_NtAllocateUserPhysicalPages_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtOpenKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtCompareTokens_return_t)(CPUState* env,target_ulong pc,uint32_t FirstTokenHandle,uint32_t SecondTokenHandle,uint32_t Equal);
typedef void (*on_NtSetIntervalProfile_enter_t)(CPUState* env,target_ulong pc,uint32_t Interval,uint32_t ClockSource);
typedef void (*on_NtReadRequestData_return_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t Message,uint32_t Index,uint32_t Buffer,uint32_t BufferLength,uint32_t ReturnLength);
typedef void (*on_NtUnlockVirtualMemory_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t NumberOfBytesToUnlock,uint32_t NumberOfBytesUnlocked);
typedef void (*on_NtSetEaFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t EaBuffer,uint32_t EaBufferSize);
typedef void (*on_NtWriteFileGather_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t BufferDescription,uint32_t BufferLength,uint32_t ByteOffset,uint32_t Key);
typedef void (*on_NtEnumerateBootEntries_return_t)(CPUState* env,target_ulong pc,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtEnumerateKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Index,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtWaitLowEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPairHandle);
typedef void (*on_NtQueryQuotaInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t Buffer,uint32_t Length,uint32_t ReturnSingleEntry,uint32_t SidList,uint32_t SidListLength,uint32_t StartSid,uint32_t RestartScan);
typedef void (*on_NtQueryIntervalProfile_return_t)(CPUState* env,target_ulong pc,uint32_t ProfileSource,uint32_t Interval);
typedef void (*on_NtQueryMutant_return_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t MutantInformationClass,uint32_t MutantInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtOpenThreadTokenEx_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t OpenAsSelf,uint32_t HandleAttributes,uint32_t TokenHandle);
typedef void (*on_NtCreateDirectoryObject_return_t)(CPUState* env,target_ulong pc,uint32_t DirectoryHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes);
typedef void (*on_NtAllocateUuids_enter_t)(CPUState* env,target_ulong pc,uint32_t Time,uint32_t Range,uint32_t Sequence,uint32_t Seed);
typedef void (*on_NtAccessCheckByTypeResultList_enter_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t PrincipalSelfSid,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t ObjectTypeList,uint32_t ObjectTypeLength,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t PrivilegeSetLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_all_sys_windows7_x86_return_t)(CPUState *env, target_ulong pc, target_ulong callno);
typedef void (*on_NtEnumerateSystemEnvironmentValuesEx_return_t)(CPUState* env,target_ulong pc,uint32_t InformationClass,uint32_t Buffer,uint32_t BufferLength);
typedef void (*on_NtRaiseHardError_enter_t)(CPUState* env,target_ulong pc,uint32_t ErrorStatus,uint32_t NumberOfParameters,uint32_t UnicodeStringParameterMask,uint32_t Parameters,uint32_t ValidResponseOptions,uint32_t Response);
typedef void (*on_NtCreateEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t EventType,uint32_t InitialState);
typedef void (*on_NtPulseEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t PulseCount);
typedef void (*on_NtDuplicateObject_enter_t)(CPUState* env,target_ulong pc,uint32_t SourceProcessHandle,uint32_t SourceHandle,uint32_t TargetProcessHandle,uint32_t TargetHandle,uint32_t DesiredAccess,uint32_t HandleAttributes,uint32_t Options);
typedef void (*on_NtTraceEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t TraceHandle,uint32_t Flags,uint32_t TraceHeaderLength,uint32_t TraceHeader);
typedef void (*on_NtCreateProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ParentProcess,uint32_t InheritObjectTable,uint32_t SectionHandle,uint32_t DebugPort,uint32_t ExceptionPort);
typedef void (*on_NtOpenProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t ClientId);
typedef void (*on_NtQueryIoCompletion_enter_t)(CPUState* env,target_ulong pc,uint32_t IoCompletionHandle,uint32_t IoCompletionInformationClass,uint32_t IoCompletionInformation,uint32_t IoCompletionInformationLength,uint32_t ResultLength);
typedef void (*on_NtReleaseMutant_enter_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t ReleaseCount);
typedef void (*on_NtOpenSemaphore_enter_t)(CPUState* env,target_ulong pc,uint32_t SemaphoreHandle,uint32_t DesiredAcces,uint32_t ObjectAttributes);
typedef void (*on_NtCreateMutant_return_t)(CPUState* env,target_ulong pc,uint32_t MutantHandle,uint32_t DesiredAccess,uint32_t ObjectAttributes,uint32_t InitialOwner);
typedef void (*on_NtQueryKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t KeyInformationClass,uint32_t KeyInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtNotifyChangeKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t CompletionFilter,uint32_t Asynchroneous,uint32_t ChangeBuffer,uint32_t Length,uint32_t WatchSubtree);
typedef void (*on_NtQueryVolumeInformationFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock,uint32_t FsInformation,uint32_t Length,uint32_t FsInformationClass);
typedef void (*on_NtQueryValueKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ValueName,uint32_t KeyValueInformationClass,uint32_t KeyValueInformation,uint32_t Length,uint32_t ResultLength);
typedef void (*on_NtSetContextThread_enter_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t Context);
typedef void (*on_NtRenameKey_enter_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle,uint32_t ReplacementName);
typedef void (*on_NtWaitForMultipleObjects_enter_t)(CPUState* env,target_ulong pc,uint32_t Count,uint32_t Object,uint32_t WaitType,uint32_t Alertable,uint32_t Time);
typedef void (*on_NtDuplicateObject_return_t)(CPUState* env,target_ulong pc,uint32_t SourceProcessHandle,uint32_t SourceHandle,uint32_t TargetProcessHandle,uint32_t TargetHandle,uint32_t DesiredAccess,uint32_t HandleAttributes,uint32_t Options);
typedef void (*on_NtUnloadKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyObjectAttributes);
typedef void (*on_NtReplyPort_enter_t)(CPUState* env,target_ulong pc,uint32_t PortHandle,uint32_t LpcReply);
typedef void (*on_NtSuspendThread_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t PreviousSuspendCount);
typedef void (*on_NtTestAlert_return_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtSetLowEventPair_enter_t)(CPUState* env,target_ulong pc,uint32_t EventPair);
typedef void (*on_NtFlushBuffersFile_enter_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock);
typedef void (*on_NtLockFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t Event,uint32_t ApcRoutine,uint32_t ApcContext,uint32_t IoStatusBlock,uint32_t ByteOffset,uint32_t Length,uint32_t Key,uint32_t FailImmediatedly,uint32_t ExclusiveLock);
typedef void (*on_NtIsProcessInJob_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t JobHandle);
typedef void (*on_NtAccessCheck_enter_t)(CPUState* env,target_ulong pc,uint32_t SecurityDescriptor,uint32_t ClientToken,uint32_t DesiredAccess,uint32_t GenericMapping,uint32_t PrivilegeSet,uint32_t ReturnLength,uint32_t GrantedAccess,uint32_t AccessStatus);
typedef void (*on_NtSuspendProcess_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle);
typedef void (*on_NtRemoveProcessDebug_enter_t)(CPUState* env,target_ulong pc,uint32_t Process,uint32_t DebugObject);
typedef void (*on_NtQueryPortInformationProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t arg0);
typedef void (*on_NtAssignProcessToJobObject_return_t)(CPUState* env,target_ulong pc,uint32_t JobHandle,uint32_t ProcessHandle);
typedef void (*on_NtFlushBuffersFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileHandle,uint32_t IoStatusBlock);
typedef void (*on_NtReadVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t BaseAddress,uint32_t Buffer,uint32_t NumberOfBytesToRead,uint32_t NumberOfBytesRead);
typedef void (*on_NtFlushKey_return_t)(CPUState* env,target_ulong pc,uint32_t KeyHandle);
typedef void (*on_NtSetEventBoostPriority_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle);
typedef void (*on_NtQuerySystemTime_return_t)(CPUState* env,target_ulong pc,uint32_t CurrentTime);
typedef void (*on_NtFreeUserPhysicalPages_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,uint32_t NumberOfPages,uint32_t UserPfnArray);
typedef void (*on_NtAllocateVirtualMemory_return_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle,target_ulong BaseAddress,uint32_t ZeroBits,uint32_t RegionSize,uint32_t AllocationType,uint32_t Protect);
typedef void (*on_NtResumeProcess_enter_t)(CPUState* env,target_ulong pc,uint32_t ProcessHandle);
typedef void (*on_NtMakePermanentObject_return_t)(CPUState* env,target_ulong pc,uint32_t Object);
typedef void (*on_NtQueryAttributesFile_return_t)(CPUState* env,target_ulong pc,uint32_t ObjectAttributes,uint32_t FileInformation);
typedef void (*on_NtCreatePagingFile_return_t)(CPUState* env,target_ulong pc,uint32_t FileName,uint32_t InitialSize,uint32_t MaxiumSize,uint32_t Reserved);
typedef void (*on_NtQueryDefaultLocale_enter_t)(CPUState* env,target_ulong pc,uint32_t UserProfile,uint32_t DefaultLocaleId);
typedef void (*on_NtOpenThreadToken_return_t)(CPUState* env,target_ulong pc,uint32_t ThreadHandle,uint32_t DesiredAccess,uint32_t OpenAsSelf,uint32_t TokenHandle);
typedef void (*on_NtReleaseKeyedEvent_return_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t Key,uint32_t Alertable,uint32_t Timeout);
typedef void (*on_NtResetEvent_enter_t)(CPUState* env,target_ulong pc,uint32_t EventHandle,uint32_t NumberOfWaitingThreads);
#endif
