//Autogenerated PPP header from /home/luke/workspace/panda/panda/plugins/taint2/taint2.h
typedef void (*on_branch2_t) (Addr, uint64_t);
void ppp_add_cb_on_branch2(on_branch2_t);
bool ppp_remove_cb_on_branch2(on_branch2_t);
typedef void (*on_indirect_jump_t) (Addr, uint64_t);
void ppp_add_cb_on_indirect_jump(on_indirect_jump_t);
bool ppp_remove_cb_on_indirect_jump(on_indirect_jump_t);
typedef void (*on_taint_change_t) (Addr, uint64_t);
void ppp_add_cb_on_taint_change(on_taint_change_t);
bool ppp_remove_cb_on_taint_change(on_taint_change_t);
typedef void (*on_taint_prop_t) (Addr, Addr, uint64_t);
void ppp_add_cb_on_taint_prop(on_taint_prop_t);
bool ppp_remove_cb_on_taint_prop(on_taint_prop_t);
typedef void (*on_ptr_load_t) (Addr, uint64_t, uint64_t);
void ppp_add_cb_on_ptr_load(on_ptr_load_t);
bool ppp_remove_cb_on_ptr_load(on_ptr_load_t);
typedef void (*on_ptr_store_t) (Addr, uint64_t, uint64_t);
void ppp_add_cb_on_ptr_store(on_ptr_store_t);
bool ppp_remove_cb_on_ptr_store(on_ptr_store_t);
typedef void (*on_after_load_t) (Addr, uint64_t, uint64_t);
void ppp_add_cb_on_after_load(on_after_load_t);
bool ppp_remove_cb_on_after_load(on_after_load_t);
typedef void (*on_after_store_t) (Addr, uint64_t, uint64_t);
void ppp_add_cb_on_after_store(on_after_store_t);
bool ppp_remove_cb_on_after_store(on_after_store_t);

