#ifdef TARGET_ARM
typedef void (*on_sys_acct_returned_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_sched_setaffinity_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_chmod_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t mode);
typedef void (*on_sys_timerfd_gettime_returned_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong otmr);
typedef void (*on_sys_sendto_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,int32_t arg5);
typedef void (*on_sys_sysctl_t)(CPUState* env,target_ulong pc,target_ulong args);
typedef void (*on_sys_lookup_dcookie_t)(CPUState* env,target_ulong pc,uint64_t cookie64,target_ulong buf,uint32_t len);
typedef void (*on_ARM_breakpoint_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setsockopt_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,int32_t optlen);
typedef void (*on_sys_fchdir_returned_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_mkdirat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t mode);
typedef void (*on_sys_io_getevents_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,int32_t min_nr,int32_t nr,target_ulong events,target_ulong timeout);
typedef void (*on_sys_utimes_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_sched_getparam_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_sendfile64_returned_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_setfsgid16_returned_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_chmod_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t mode);
typedef void (*on_sys_timer_delete_returned_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_vmsplice_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong iov,uint32_t nr_segs,uint32_t flags);
typedef void (*on_sys_lchown16_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_nice_returned_t)(CPUState* env,target_ulong pc,int32_t increment);
typedef void (*on_sys_rt_sigprocmask_returned_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset,uint32_t sigsetsize);
typedef void (*on_sys_dup2_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd);
typedef void (*on_sys_personality_returned_t)(CPUState* env,target_ulong pc,int32_t personality);
typedef void (*on_sys_chown_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_getgid16_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_eventfd_t)(CPUState* env,target_ulong pc,uint32_t count);
typedef void (*on_sys_recv_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_mq_unlink_returned_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_ioctl_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_mkdir_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_gettid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_umount_returned_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t flags);
typedef void (*on_sys_reboot_t)(CPUState* env,target_ulong pc,int32_t magic1,int32_t magic2,uint32_t cmd,target_ulong arg);
typedef void (*on_sys_write_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_getresgid16_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_fsetxattr_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_mknod_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_fstatfs_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf);
typedef void (*on_sys_personality_t)(CPUState* env,target_ulong pc,int32_t personality);
typedef void (*on_sys_fcntl64_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_fork_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fchmodat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t mode);
typedef void (*on_sys_sched_getparam_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_exit_group_returned_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_setdomainname_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_ARM_cacheflush_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t end,uint32_t flags);
typedef void (*on_sys_setreuid16_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_msgget_returned_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t msgflg);
typedef void (*on_sys_getxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_write_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_ftruncate64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint64_t length);
typedef void (*on_sys_getpriority_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_socketpair_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2,target_ulong arg3);
typedef void (*on_sys_getresuid16_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_openat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_clock_gettime_returned_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_dup3_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd,int32_t flags);
typedef void (*on_sys_socket_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2);
typedef void (*on_sys_msync_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t flags);
typedef void (*on_sys_mq_timedreceive_returned_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,target_ulong msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_nice_t)(CPUState* env,target_ulong pc,int32_t increment);
typedef void (*on_sys_ptrace_t)(CPUState* env,target_ulong pc,int32_t request,int32_t pid,int32_t addr,int32_t data_arg);
typedef void (*on_sys_getpeername_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_geteuid16_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getgroups16_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_arm_mremap_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t old_len,uint32_t new_len,uint32_t flags,uint32_t new_addr);
typedef void (*on_sys_msgctl_t)(CPUState* env,target_ulong pc,int32_t msqid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_inotify_add_watch_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong path,uint32_t mask);
typedef void (*on_sys_epoll_create_t)(CPUState* env,target_ulong pc,int32_t size);
typedef void (*on_sys_sync_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_inotify_init_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getuid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sched_setparam_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_utimes_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_statfs_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf);
typedef void (*on_sys_setgroups16_returned_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_fstatat64_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong statbuf,int32_t flag);
typedef void (*on_do_mmap2_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len,uint32_t prot,uint32_t flags,uint32_t fd,uint32_t pgoff);
typedef void (*on_sys_setsid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sigreturn_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_umask_t)(CPUState* env,target_ulong pc,int32_t mask);
typedef void (*on_sys_newlstat_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_sched_get_priority_max_returned_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_setgroups_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_getpgid_returned_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_getgroups_returned_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_io_setup_returned_t)(CPUState* env,target_ulong pc,uint32_t nr_reqs,target_ulong ctx);
typedef void (*on_sys_clock_nanosleep_t)(CPUState* env,target_ulong pc,uint32_t which_clock,int32_t flags,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_timer_getoverrun_returned_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_sched_get_priority_max_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_ARM_cmpxchg_returned_t)(CPUState* env,target_ulong pc,uint32_t val,uint32_t src,target_ulong dest);
typedef void (*on_sys_msgget_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t msgflg);
typedef void (*on_sys_delete_module_t)(CPUState* env,target_ulong pc,target_ulong name_user,uint32_t flags);
typedef void (*on_sys_setxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_timerfd_settime_returned_t)(CPUState* env,target_ulong pc,int32_t ufd,int32_t flags,target_ulong utmr,target_ulong otmr);
typedef void (*on_sys_getrlimit_returned_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_getdents_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_getitimer_returned_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value);
typedef void (*on_sigaction_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact);
typedef void (*on_sys_getcpu_returned_t)(CPUState* env,target_ulong pc,target_ulong cpu,target_ulong node,target_ulong cache);
typedef void (*on_sys_fsync_returned_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_munmap_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len);
typedef void (*on_sys_select_t)(CPUState* env,target_ulong pc,int32_t n,target_ulong inp,target_ulong outp,target_ulong exp,target_ulong tvp);
typedef void (*on_sys_timer_create_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong timer_event_spec,target_ulong created_timer_id);
typedef void (*on_sys_mq_timedsend_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,uint32_t msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_clock_settime_returned_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_link_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_fcntl64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_set_robust_list_t)(CPUState* env,target_ulong pc,target_ulong head,uint32_t len);
typedef void (*on_sys_fremovexattr_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name);
typedef void (*on_sys_getpriority_returned_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_signalfd4_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask,int32_t flags);
typedef void (*on_sys_flock_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd);
typedef void (*on_sys_stat64_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_setxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_vfork_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_pread64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_tkill_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_fcntl_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_getdents_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_getgid16_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_shutdown_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_sync_file_range2_returned_t)(CPUState* env,target_ulong pc,int32_t fd,uint32_t flags,uint64_t offset,uint64_t nbytes);
typedef void (*on_ARM_set_tls_returned_t)(CPUState* env,target_ulong pc,uint32_t arg);
typedef void (*on_sys_writev_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_madvise_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t behavior);
typedef void (*on_sys_ftruncate64_t)(CPUState* env,target_ulong pc,uint32_t fd,uint64_t length);
typedef void (*on_sys_timerfd_create_returned_t)(CPUState* env,target_ulong pc,int32_t clockid,int32_t flags);
typedef void (*on_ARM_cacheflush_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t end,uint32_t flags);
typedef void (*on_sys_io_getevents_returned_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,int32_t min_nr,int32_t nr,target_ulong events,target_ulong timeout);
typedef void (*on_sys_mq_notify_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong notification);
typedef void (*on_sys_fgetxattr_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_getgid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_munlock_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_getitimer_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value);
typedef void (*on_sys_truncate_returned_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t length);
typedef void (*on_sys_eventfd_returned_t)(CPUState* env,target_ulong pc,uint32_t count);
typedef void (*on_sys_tgkill_t)(CPUState* env,target_ulong pc,int32_t tgid,int32_t pid,int32_t sig);
typedef void (*on_sys_ioprio_set_returned_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t ioprio);
typedef void (*on_sys_sysfs_returned_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg1,uint32_t arg2);
typedef void (*on_sys_fchown_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_setfsuid_returned_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_setresgid_returned_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_exit_returned_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_clock_getres_returned_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_fchown_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_tee_t)(CPUState* env,target_ulong pc,int32_t fdin,int32_t fdout,uint32_t len,uint32_t flags);
typedef void (*on_sys_ftruncate_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t length);
typedef void (*on_sys_setresgid16_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_clone_t)(CPUState* env,target_ulong pc,uint32_t clone_flags,uint32_t newsp,target_ulong parent_tidptr,int32_t tls_val,target_ulong child_tidptr,target_ulong regs);
typedef void (*on_sys_munlockall_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_rt_sigtimedwait_returned_t)(CPUState* env,target_ulong pc,target_ulong uthese,target_ulong uinfo,target_ulong uts,uint32_t sigsetsize);
typedef void (*on_sys_mq_timedreceive_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,target_ulong msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_capset_returned_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong data_arg);
typedef void (*on_sys_setregid_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_pause_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sync_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_reboot_returned_t)(CPUState* env,target_ulong pc,int32_t magic1,int32_t magic2,uint32_t cmd,target_ulong arg);
typedef void (*on_sys_madvise_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t behavior);
typedef void (*on_sys_fcntl_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_ioprio_get_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_rt_sigtimedwait_t)(CPUState* env,target_ulong pc,target_ulong uthese,target_ulong uinfo,target_ulong uts,uint32_t sigsetsize);
typedef void (*on_sys_add_key_returned_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _payload,uint32_t plen,uint32_t destringid);
typedef void (*on_sys_msgsnd_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgflg);
typedef void (*on_sys_restart_syscall_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getuid16_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fremovexattr_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name);
typedef void (*on_sys_mq_open_returned_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t oflag,uint32_t mode,target_ulong attr);
typedef void (*on_sys_accept_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_mq_unlink_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_timerfd_gettime_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong otmr);
typedef void (*on_sys_symlink_t)(CPUState* env,target_ulong pc,target_ulong old,target_ulong anew);
typedef void (*on_sys_gettimeofday_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_timer_settime_t)(CPUState* env,target_ulong pc,uint32_t timer_id,int32_t flags,target_ulong new_setting,target_ulong old_setting);
typedef void (*on_sys_timer_gettime_t)(CPUState* env,target_ulong pc,uint32_t timer_id,target_ulong setting);
typedef void (*on_sigsuspend_returned_t)(CPUState* env,target_ulong pc,int32_t restart,uint32_t oldmask,uint32_t mask);
typedef void (*on_sys_lseek_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset,uint32_t origin);
typedef void (*on_sys_times_t)(CPUState* env,target_ulong pc,target_ulong tbuf);
typedef void (*on_sys_socket_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2);
typedef void (*on_sys_keyctl_returned_t)(CPUState* env,target_ulong pc,int32_t cmd,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_pciconfig_iobase_returned_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t bus,uint32_t devfn);
typedef void (*on_sys_pread64_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_gettid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_munlock_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_fstatat64_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong statbuf,int32_t flag);
typedef void (*on_sys_epoll_create1_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_sigpending_t)(CPUState* env,target_ulong pc,target_ulong set);
typedef void (*on_sys_close_returned_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_readlink_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_mbind_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t mode,target_ulong nmask,uint32_t maxnode,uint32_t flags);
typedef void (*on_sys_flock_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd);
typedef void (*on_sys_swapon_t)(CPUState* env,target_ulong pc,target_ulong specialfile,int32_t swap_flags);
typedef void (*on_sys_getsockname_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_shmat_returned_t)(CPUState* env,target_ulong pc,int32_t shmid,target_ulong shmaddr,int32_t shmflg);
typedef void (*on_sys_msgsnd_returned_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgflg);
typedef void (*on_sys_setfsuid_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_semtimedop_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops,target_ulong timeout);
typedef void (*on_sys_sched_yield_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getresuid_returned_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_setfsuid16_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_setfsgid16_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_semctl_t)(CPUState* env,target_ulong pc,int32_t semid,int32_t semnum,int32_t cmd,uint32_t arg);
typedef void (*on_sys_fchmod_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t mode);
typedef void (*on_sys_readv_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_rt_sigaction_returned_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact,uint32_t sigsetsize);
typedef void (*on_sys_fstatfs64_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t sz,target_ulong buf);
typedef void (*on_sys_setreuid16_returned_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_shmget_returned_t)(CPUState* env,target_ulong pc,uint32_t key,uint32_t size,int32_t flag);
typedef void (*on_sys_init_module_returned_t)(CPUState* env,target_ulong pc,target_ulong umod,uint32_t len,target_ulong uargs);
typedef void (*on_sys_nanosleep_t)(CPUState* env,target_ulong pc,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_rt_sigprocmask_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset,uint32_t sigsetsize);
typedef void (*on_sys_removexattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_execve_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong argv,target_ulong envp);
typedef void (*on_sys_brk_returned_t)(CPUState* env,target_ulong pc,uint32_t brk);
typedef void (*on_sys_llistxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_pivot_root_t)(CPUState* env,target_ulong pc,target_ulong new_root,target_ulong put_old);
typedef void (*on_sys_pciconfig_write_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_uselib_t)(CPUState* env,target_ulong pc,target_ulong library);
typedef void (*on_ARM_cmpxchg_t)(CPUState* env,target_ulong pc,uint32_t val,uint32_t src,target_ulong dest);
typedef void (*on_sys_getpgrp_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setregid_returned_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_readahead_t)(CPUState* env,target_ulong pc,int32_t fd,uint64_t offset,uint32_t count);
typedef void (*on_sys_timer_settime_returned_t)(CPUState* env,target_ulong pc,uint32_t timer_id,int32_t flags,target_ulong new_setting,target_ulong old_setting);
typedef void (*on_sys_fstat64_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_nfsservctl_t)(CPUState* env,target_ulong pc,int32_t cmd,target_ulong arg,target_ulong res);
typedef void (*on_sys_sendfile_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sigaction_returned_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact);
typedef void (*on_sys_getresuid16_returned_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_sysfs_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg1,uint32_t arg2);
typedef void (*on_sys_mq_getsetattr_returned_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong mqstat,target_ulong omqstat);
typedef void (*on_sys_vmsplice_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong iov,uint32_t nr_segs,uint32_t flags);
typedef void (*on_sys_io_submit_t)(CPUState* env,target_ulong pc,uint32_t arg0,int32_t arg1,target_ulong arg2);
typedef void (*on_sys_quotactl_returned_t)(CPUState* env,target_ulong pc,uint32_t cmd,target_ulong special,uint32_t id,target_ulong addr);
typedef void (*on_sys_symlinkat_t)(CPUState* env,target_ulong pc,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_io_destroy_t)(CPUState* env,target_ulong pc,uint32_t ctx);
typedef void (*on_sys_request_key_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _callout_info,uint32_t destringid);
typedef void (*on_sys_fstat64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_setregid16_returned_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_set_tid_address_returned_t)(CPUState* env,target_ulong pc,target_ulong tidptr);
typedef void (*on_sys_sched_get_priority_min_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_waitid_returned_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t pid,target_ulong infop,int32_t options,target_ulong ru);
typedef void (*on_sys_lstat64_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_pwrite64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_getegid16_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fstatfs_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf);
typedef void (*on_sys_pipe_t)(CPUState* env,target_ulong pc,target_ulong arg0);
typedef void (*on_sys_clock_gettime_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_setrlimit_returned_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_timer_gettime_returned_t)(CPUState* env,target_ulong pc,uint32_t timer_id,target_ulong setting);
typedef void (*on_sys_remap_file_pages_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t size,uint32_t prot,uint32_t pgoff,uint32_t flags);
typedef void (*on_sys_splice_t)(CPUState* env,target_ulong pc,int32_t fd_in,target_ulong off_in,int32_t fd_out,target_ulong off_out,uint32_t len,uint32_t flags);
typedef void (*on_sigsuspend_t)(CPUState* env,target_ulong pc,int32_t restart,uint32_t oldmask,uint32_t mask);
typedef void (*on_sys_fstatfs64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t sz,target_ulong buf);
typedef void (*on_sys_inotify_add_watch_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong path,uint32_t mask);
typedef void (*on_sys_newfstat_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_lsetxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_inotify_init1_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_sched_setscheduler_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,int32_t policy,target_ulong param);
typedef void (*on_sys_getegid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_settimeofday_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_unlinkat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t flag);
typedef void (*on_sys_listen_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_get_mempolicy_returned_t)(CPUState* env,target_ulong pc,target_ulong policy,target_ulong nmask,uint32_t maxnode,uint32_t addr,uint32_t flags);
typedef void (*on_sys_mlock_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_statfs64_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t sz,target_ulong buf);
typedef void (*on_sys_swapoff_returned_t)(CPUState* env,target_ulong pc,target_ulong specialfile);
typedef void (*on_sys_lseek_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset,uint32_t origin);
typedef void (*on_sys_fchmod_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t mode);
typedef void (*on_sys_newstat_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_set_tid_address_t)(CPUState* env,target_ulong pc,target_ulong tidptr);
typedef void (*on_sys_flistxattr_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong list,uint32_t size);
typedef void (*on_sys_getresgid_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_shmdt_returned_t)(CPUState* env,target_ulong pc,target_ulong shmaddr);
typedef void (*on_sys_fchownat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t user,uint32_t group,int32_t flag);
typedef void (*on_sys_setitimer_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value,target_ulong ovalue);
typedef void (*on_sys_fchown16_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_request_key_returned_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _callout_info,uint32_t destringid);
typedef void (*on_sys_setresuid_returned_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_bdflush_t)(CPUState* env,target_ulong pc,int32_t func,int32_t data_arg);
typedef void (*on_sys_getrusage_t)(CPUState* env,target_ulong pc,int32_t who,target_ulong ru);
typedef void (*on_sys_shmctl_returned_t)(CPUState* env,target_ulong pc,int32_t shmid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_mount_returned_t)(CPUState* env,target_ulong pc,target_ulong dev_name,target_ulong dir_name,target_ulong type,uint32_t flags,target_ulong data_arg);
typedef void (*on_sys_setresuid16_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_timer_getoverrun_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_sysctl_returned_t)(CPUState* env,target_ulong pc,target_ulong args);
typedef void (*on_sys_io_destroy_returned_t)(CPUState* env,target_ulong pc,uint32_t ctx);
typedef void (*on_sys_nfsservctl_returned_t)(CPUState* env,target_ulong pc,int32_t cmd,target_ulong arg,target_ulong res);
typedef void (*on_sys_sched_yield_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_inotify_init1_returned_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_ARM_user26_mode_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_tee_returned_t)(CPUState* env,target_ulong pc,int32_t fdin,int32_t fdout,uint32_t len,uint32_t flags);
typedef void (*on_sys_rt_sigsuspend_t)(CPUState* env,target_ulong pc,target_ulong unewset,uint32_t sigsetsize);
typedef void (*on_sys_fsetxattr_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_kexec_load_t)(CPUState* env,target_ulong pc,uint32_t entry,uint32_t nr_segments,target_ulong segments,uint32_t flags);
typedef void (*on_sys_chroot_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_getpid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_dup3_returned_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd,int32_t flags);
typedef void (*on_sys_poll_returned_t)(CPUState* env,target_ulong pc,target_ulong ufds,uint32_t nfds,int32_t timeout);
typedef void (*on_sys_linkat_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname,int32_t flags);
typedef void (*on_sys_remap_file_pages_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t size,uint32_t prot,uint32_t pgoff,uint32_t flags);
typedef void (*on_sys_send_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_eventfd2_t)(CPUState* env,target_ulong pc,uint32_t count,int32_t flags);
typedef void (*on_sys_sysinfo_returned_t)(CPUState* env,target_ulong pc,target_ulong info);
typedef void (*on_sys_io_submit_returned_t)(CPUState* env,target_ulong pc,uint32_t arg0,int32_t arg1,target_ulong arg2);
typedef void (*on_ARM_usr32_mode_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_close_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_rt_sigpending_returned_t)(CPUState* env,target_ulong pc,target_ulong set,uint32_t sigsetsize);
typedef void (*on_sys_semget_returned_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t nsems,int32_t semflg);
typedef void (*on_sys_sched_getaffinity_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_llseek_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset_high,uint32_t offset_low,target_ulong result,uint32_t origin);
typedef void (*on_sys_epoll_ctl_returned_t)(CPUState* env,target_ulong pc,int32_t epfd,int32_t op,int32_t fd,target_ulong event);
typedef void (*on_sys_getsockname_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_unlink_returned_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_chown16_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_pciconfig_read_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_sendto_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,int32_t arg5);
typedef void (*on_sys_chroot_returned_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_signalfd_returned_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask);
typedef void (*on_sys_mincore_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,target_ulong vec);
typedef void (*on_sys_fgetxattr_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_getuid16_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sched_getscheduler_returned_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_setpgid_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t pgid);
typedef void (*on_execve_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong argv,target_ulong envp);
typedef void (*on_sys_set_mempolicy_t)(CPUState* env,target_ulong pc,int32_t mode,target_ulong nmask,uint32_t maxnode);
typedef void (*on_sys_kexec_load_returned_t)(CPUState* env,target_ulong pc,uint32_t entry,uint32_t nr_segments,target_ulong segments,uint32_t flags);
typedef void (*on_sys_getdents64_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_bind_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_sethostname_returned_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_listxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_sync_file_range2_t)(CPUState* env,target_ulong pc,int32_t fd,uint32_t flags,uint64_t offset,uint64_t nbytes);
typedef void (*on_sys_timer_delete_t)(CPUState* env,target_ulong pc,uint32_t timer_id);
typedef void (*on_sys_newuname_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_ARM_breakpoint_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getcpu_t)(CPUState* env,target_ulong pc,target_ulong cpu,target_ulong node,target_ulong cache);
typedef void (*on_sys_sethostname_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_inotify_init_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getegid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_sigprocmask_returned_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset);
typedef void (*on_sys_setrlimit_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_inotify_rm_watch_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t wd);
typedef void (*on_sys_semget_t)(CPUState* env,target_ulong pc,uint32_t key,int32_t nsems,int32_t semflg);
typedef void (*on_sys_getpeername_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_lremovexattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_mlockall_returned_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_capget_returned_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong dataptr);
typedef void (*on_sys_prctl_returned_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_mkdirat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t mode);
typedef void (*on_sys_getsockopt_returned_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,target_ulong optlen);
typedef void (*on_sys_getppid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_symlinkat_returned_t)(CPUState* env,target_ulong pc,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_getsockopt_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,target_ulong optlen);
typedef void (*on_sys_statfs_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf);
typedef void (*on_sys_syslog_returned_t)(CPUState* env,target_ulong pc,int32_t type,target_ulong buf,int32_t len);
typedef void (*on_ARM_usr32_mode_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_renameat_returned_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_uselib_returned_t)(CPUState* env,target_ulong pc,target_ulong library);
typedef void (*on_sys_epoll_create1_returned_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_sigpending_returned_t)(CPUState* env,target_ulong pc,target_ulong set);
typedef void (*on_sys_mq_open_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t oflag,uint32_t mode,target_ulong attr);
typedef void (*on_sys_setgid16_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_fdatasync_returned_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_adjtimex_t)(CPUState* env,target_ulong pc,target_ulong txc_p);
typedef void (*on_sys_sched_getscheduler_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_setfsgid_returned_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_rt_sigqueueinfo_returned_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig,target_ulong uinfo);
typedef void (*on_sys_move_pages_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t nr_pages,target_ulong pages,target_ulong nodes,target_ulong status,int32_t flags);
typedef void (*on_sys_munlockall_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setfsgid_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_rename_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_swapoff_t)(CPUState* env,target_ulong pc,target_ulong specialfile);
typedef void (*on_sys_setuid16_returned_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_utimensat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes,int32_t flags);
typedef void (*on_sys_splice_returned_t)(CPUState* env,target_ulong pc,int32_t fd_in,target_ulong off_in,int32_t fd_out,target_ulong off_out,uint32_t len,uint32_t flags);
typedef void (*on_sys_vhangup_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setsid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_unshare_returned_t)(CPUState* env,target_ulong pc,uint32_t unshare_flags);
typedef void (*on_sys_io_cancel_returned_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,target_ulong iocb,target_ulong result);
typedef void (*on_sys_unlinkat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong pathname,int32_t flag);
typedef void (*on_sys_setuid16_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_mbind_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t mode,target_ulong nmask,uint32_t maxnode,uint32_t flags);
typedef void (*on_sys_lookup_dcookie_returned_t)(CPUState* env,target_ulong pc,uint64_t cookie64,target_ulong buf,uint32_t len);
typedef void (*on_do_sigaltstack_returned_t)(CPUState* env,target_ulong pc,target_ulong uss,target_ulong uoss);
typedef void (*on_sys_open_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_bdflush_returned_t)(CPUState* env,target_ulong pc,int32_t func,int32_t data_arg);
typedef void (*on_ARM_null_segfault_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_dup_returned_t)(CPUState* env,target_ulong pc,uint32_t fildes);
typedef void (*on_sys_syslog_t)(CPUState* env,target_ulong pc,int32_t type,target_ulong buf,int32_t len);
typedef void (*on_sys_unshare_t)(CPUState* env,target_ulong pc,uint32_t unshare_flags);
typedef void (*on_sys_mlockall_t)(CPUState* env,target_ulong pc,int32_t flags);
typedef void (*on_sys_open_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_chown16_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_epoll_create_returned_t)(CPUState* env,target_ulong pc,int32_t size);
typedef void (*on_sys_nanosleep_returned_t)(CPUState* env,target_ulong pc,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_readv_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_sched_setparam_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong param);
typedef void (*on_sys_acct_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_utimensat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes,int32_t flags);
typedef void (*on_sys_ustat_returned_t)(CPUState* env,target_ulong pc,uint32_t dev,target_ulong ubuf);
typedef void (*on_sys_sched_get_priority_min_returned_t)(CPUState* env,target_ulong pc,int32_t policy);
typedef void (*on_sys_lgetxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_mprotect_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t prot);
typedef void (*on_sys_wait4_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong stat_addr,int32_t options,target_ulong ru);
typedef void (*on_sys_setregid16_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid);
typedef void (*on_sys_chdir_returned_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_mincore_returned_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,target_ulong vec);
typedef void (*on_sys_exit_group_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_setreuid_returned_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_mprotect_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,uint32_t prot);
typedef void (*on_sys_symlink_returned_t)(CPUState* env,target_ulong pc,target_ulong old,target_ulong anew);
typedef void (*on_sys_clock_settime_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_truncate_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t length);
typedef void (*on_sys_rt_sigsuspend_returned_t)(CPUState* env,target_ulong pc,target_ulong unewset,uint32_t sigsetsize);
typedef void (*on_sys_setgid_returned_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_readlinkat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_timerfd_create_t)(CPUState* env,target_ulong pc,int32_t clockid,int32_t flags);
typedef void (*on_sys_getpid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_setresuid_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_ARM_null_segfault_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_tkill_returned_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_get_robust_list_returned_t)(CPUState* env,target_ulong pc,int32_t pid,target_ulong head_ptr,target_ulong len_ptr);
typedef void (*on_clone_returned_t)(CPUState* env,target_ulong pc,uint32_t clone_flags,uint32_t newsp,target_ulong parent_tidptr,int32_t tls_val,target_ulong child_tidptr,target_ulong regs);
typedef void (*on_sys_setuid_returned_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_newstat_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_setsockopt_returned_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t level,int32_t optname,target_ulong optval,int32_t optlen);
typedef void (*on_sys_faccessat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode);
typedef void (*on_sys_socketpair_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1,int32_t arg2,target_ulong arg3);
typedef void (*on_sys_mlock_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len);
typedef void (*on_sys_read_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_capset_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong data_arg);
typedef void (*on_sys_sigprocmask_t)(CPUState* env,target_ulong pc,int32_t how,target_ulong set,target_ulong oset);
typedef void (*on_sys_ioprio_get_returned_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who);
typedef void (*on_sys_shmat_t)(CPUState* env,target_ulong pc,int32_t shmid,target_ulong shmaddr,int32_t shmflg);
typedef void (*on_sys_send_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_semctl_returned_t)(CPUState* env,target_ulong pc,int32_t semid,int32_t semnum,int32_t cmd,uint32_t arg);
typedef void (*on_sys_eventfd2_returned_t)(CPUState* env,target_ulong pc,uint32_t count,int32_t flags);
typedef void (*on_sys_sendmsg_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_recvfrom_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,target_ulong arg5);
typedef void (*on_sys_getrusage_returned_t)(CPUState* env,target_ulong pc,int32_t who,target_ulong ru);
typedef void (*on_sys_flistxattr_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong list,uint32_t size);
typedef void (*on_sys_pipe2_returned_t)(CPUState* env,target_ulong pc,target_ulong arg0,int32_t arg1);
typedef void (*on_sys_newlstat_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_sched_setaffinity_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_gettimeofday_returned_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_semtimedop_returned_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops,target_ulong timeout);
typedef void (*on_sys_geteuid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_io_cancel_t)(CPUState* env,target_ulong pc,uint32_t ctx_id,target_ulong iocb,target_ulong result);
typedef void (*on_ARM_set_tls_t)(CPUState* env,target_ulong pc,uint32_t arg);
typedef void (*on_sys_exit_t)(CPUState* env,target_ulong pc,int32_t error_code);
typedef void (*on_sys_swapon_returned_t)(CPUState* env,target_ulong pc,target_ulong specialfile,int32_t swap_flags);
typedef void (*on_sys_creat_returned_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_signalfd4_returned_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask,int32_t flags);
typedef void (*on_sys_semop_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops);
typedef void (*on_sys_openat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t flags,int32_t mode);
typedef void (*on_sys_rt_sigpending_t)(CPUState* env,target_ulong pc,target_ulong set,uint32_t sigsetsize);
typedef void (*on_sys_newuname_returned_t)(CPUState* env,target_ulong pc,target_ulong name);
typedef void (*on_sys_listen_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_geteuid16_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_timer_create_returned_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong timer_event_spec,target_ulong created_timer_id);
typedef void (*on_sys_getgroups_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_mq_getsetattr_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong mqstat,target_ulong omqstat);
typedef void (*on_sys_lchown_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_times_returned_t)(CPUState* env,target_ulong pc,target_ulong tbuf);
typedef void (*on_sys_add_key_t)(CPUState* env,target_ulong pc,target_ulong _type,target_ulong _description,target_ulong _payload,uint32_t plen,uint32_t destringid);
typedef void (*on_sys_ioctl_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t cmd,uint32_t arg);
typedef void (*on_sys_io_setup_t)(CPUState* env,target_ulong pc,uint32_t nr_reqs,target_ulong ctx);
typedef void (*on_sys_msync_t)(CPUState* env,target_ulong pc,uint32_t start,uint32_t len,int32_t flags);
typedef void (*on_sys_connect_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_munmap_returned_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len);
typedef void (*on_sys_fallocate_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t mode,uint64_t offset,uint64_t len);
typedef void (*on_sys_connect_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_select_returned_t)(CPUState* env,target_ulong pc,int32_t n,target_ulong inp,target_ulong outp,target_ulong exp,target_ulong tvp);
typedef void (*on_sys_recvfrom_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3,target_ulong arg4,target_ulong arg5);
typedef void (*on_sys_getcwd_returned_t)(CPUState* env,target_ulong pc,target_ulong buf,uint32_t size);
typedef void (*on_sys_settimeofday_returned_t)(CPUState* env,target_ulong pc,target_ulong tv,target_ulong tz);
typedef void (*on_sys_accept_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,target_ulong arg2);
typedef void (*on_sys_msgrcv_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgtyp,int32_t msgflg);
typedef void (*on_sigreturn_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_fdatasync_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_recvmsg_returned_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_set_robust_list_returned_t)(CPUState* env,target_ulong pc,target_ulong head,uint32_t len);
typedef void (*on_sys_fchownat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t user,uint32_t group,int32_t flag);
typedef void (*on_sys_recv_returned_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,uint32_t arg2,uint32_t arg3);
typedef void (*on_sys_adjtimex_returned_t)(CPUState* env,target_ulong pc,target_ulong txc_p);
typedef void (*on_sys_signalfd_t)(CPUState* env,target_ulong pc,int32_t ufd,target_ulong user_mask,uint32_t sizemask);
typedef void (*on_sys_listxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_mknod_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_fchdir_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_readlinkat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_pause_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getsid_returned_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_get_robust_list_t)(CPUState* env,target_ulong pc,int32_t pid,target_ulong head_ptr,target_ulong len_ptr);
typedef void (*on_sys_setgroups16_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_fallocate_returned_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t mode,uint64_t offset,uint64_t len);
typedef void (*on_sys_chown_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_mq_timedsend_returned_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong msg_ptr,uint32_t msg_len,uint32_t msg_prio,target_ulong abs_timeout);
typedef void (*on_sys_futex_returned_t)(CPUState* env,target_ulong pc,target_ulong uaddr,int32_t op,uint32_t val,target_ulong utime,target_ulong uaddr2,uint32_t val3);
typedef void (*on_sys_setreuid_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid);
typedef void (*on_sys_brk_t)(CPUState* env,target_ulong pc,uint32_t brk);
typedef void (*on_sys_getresgid16_returned_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_lremovexattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_access_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode);
typedef void (*on_sys_sendmsg_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_sys_restart_syscall_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_lstat64_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_sys_setresgid16_returned_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_lsetxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size,int32_t flags);
typedef void (*on_sys_prctl_t)(CPUState* env,target_ulong pc,int32_t option,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_msgrcv_returned_t)(CPUState* env,target_ulong pc,int32_t msqid,target_ulong msgp,uint32_t msgsz,int32_t msgtyp,int32_t msgflg);
typedef void (*on_sys_arm_fadvise64_64_returned_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t advice,uint64_t offset,uint64_t len);
typedef void (*on_sys_shmctl_t)(CPUState* env,target_ulong pc,int32_t shmid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_ptrace_returned_t)(CPUState* env,target_ulong pc,int32_t request,int32_t pid,int32_t addr,int32_t data_arg);
typedef void (*on_sys_delete_module_returned_t)(CPUState* env,target_ulong pc,target_ulong name_user,uint32_t flags);
typedef void (*on_sys_setpriority_returned_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t niceval);
typedef void (*on_sys_clock_nanosleep_returned_t)(CPUState* env,target_ulong pc,uint32_t which_clock,int32_t flags,target_ulong rqtp,target_ulong rmtp);
typedef void (*on_sys_setresuid16_returned_t)(CPUState* env,target_ulong pc,uint32_t ruid,uint32_t euid,uint32_t suid);
typedef void (*on_sys_sched_rr_get_interval_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong interval);
typedef void (*on_sys_kill_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_llistxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong list,uint32_t size);
typedef void (*on_sys_setpriority_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t niceval);
typedef void (*on_sys_pivot_root_returned_t)(CPUState* env,target_ulong pc,target_ulong new_root,target_ulong put_old);
typedef void (*on_sys_sched_getaffinity_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t len,target_ulong user_mask_ptr);
typedef void (*on_sys_fchmodat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,uint32_t mode);
typedef void (*on_sys_getxattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_pciconfig_iobase_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t bus,uint32_t devfn);
typedef void (*on_sys_lchown_returned_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_mknodat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_access_t)(CPUState* env,target_ulong pc,target_ulong filename,int32_t mode);
typedef void (*on_sys_shmdt_t)(CPUState* env,target_ulong pc,target_ulong shmaddr);
typedef void (*on_sys_tgkill_returned_t)(CPUState* env,target_ulong pc,int32_t tgid,int32_t pid,int32_t sig);
typedef void (*on_sys_getdents64_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong dirent,uint32_t count);
typedef void (*on_sys_futex_t)(CPUState* env,target_ulong pc,target_ulong uaddr,int32_t op,uint32_t val,target_ulong utime,target_ulong uaddr2,uint32_t val3);
typedef void (*on_sys_recvmsg_t)(CPUState* env,target_ulong pc,int32_t fd,target_ulong msg,uint32_t flags);
typedef void (*on_arm_mremap_returned_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t old_len,uint32_t new_len,uint32_t flags,uint32_t new_addr);
typedef void (*on_sys_rmdir_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_setfsuid16_returned_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_pwrite64_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count,uint64_t pos);
typedef void (*on_sys_arm_fadvise64_64_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t advice,uint64_t offset,uint64_t len);
typedef void (*on_sys_getgroups16_returned_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_bind_t)(CPUState* env,target_ulong pc,int32_t arg0,target_ulong arg1,int32_t arg2);
typedef void (*on_sys_rt_sigqueueinfo_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig,target_ulong uinfo);
typedef void (*on_sys_renameat_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname);
typedef void (*on_sys_futimesat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_timerfd_settime_t)(CPUState* env,target_ulong pc,int32_t ufd,int32_t flags,target_ulong utmr,target_ulong otmr);
typedef void (*on_sys_getcwd_t)(CPUState* env,target_ulong pc,target_ulong buf,uint32_t size);
typedef void (*on_sys_getsid_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_msgctl_returned_t)(CPUState* env,target_ulong pc,int32_t msqid,int32_t cmd,target_ulong buf);
typedef void (*on_sys_sysinfo_t)(CPUState* env,target_ulong pc,target_ulong info);
typedef void (*on_sys_ftruncate_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t length);
typedef void (*on_sys_lchown16_t)(CPUState* env,target_ulong pc,target_ulong filename,uint32_t user,uint32_t group);
typedef void (*on_sys_mount_t)(CPUState* env,target_ulong pc,target_ulong dev_name,target_ulong dir_name,target_ulong type,uint32_t flags,target_ulong data_arg);
typedef void (*on_sys_readahead_returned_t)(CPUState* env,target_ulong pc,int32_t fd,uint64_t offset,uint32_t count);
typedef void (*on_do_sigaltstack_t)(CPUState* env,target_ulong pc,target_ulong uss,target_ulong uoss);
typedef void (*on_sys_setgid16_returned_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_poll_t)(CPUState* env,target_ulong pc,target_ulong ufds,uint32_t nfds,int32_t timeout);
typedef void (*on_sys_move_pages_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t nr_pages,target_ulong pages,target_ulong nodes,target_ulong status,int32_t flags);
typedef void (*on_sys_dup2_returned_t)(CPUState* env,target_ulong pc,uint32_t oldfd,uint32_t newfd);
typedef void (*on_sys_getegid16_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_rename_returned_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_geteuid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_lgetxattr_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name,target_ulong value,uint32_t size);
typedef void (*on_sys_dup_t)(CPUState* env,target_ulong pc,uint32_t fildes);
typedef void (*on_sys_sched_setscheduler_t)(CPUState* env,target_ulong pc,uint32_t pid,int32_t policy,target_ulong param);
typedef void (*on_sys_semop_returned_t)(CPUState* env,target_ulong pc,int32_t semid,target_ulong sops,uint32_t nsops);
typedef void (*on_sys_getresgid_returned_t)(CPUState* env,target_ulong pc,target_ulong rgid,target_ulong egid,target_ulong sgid);
typedef void (*on_sys_getrlimit_t)(CPUState* env,target_ulong pc,uint32_t resource,target_ulong rlim);
typedef void (*on_sys_setitimer_returned_t)(CPUState* env,target_ulong pc,int32_t which,target_ulong value,target_ulong ovalue);
typedef void (*on_sys_pipe_returned_t)(CPUState* env,target_ulong pc,target_ulong arg0);
typedef void (*on_sys_quotactl_t)(CPUState* env,target_ulong pc,uint32_t cmd,target_ulong special,uint32_t id,target_ulong addr);
typedef void (*on_sys_faccessat_returned_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode);
typedef void (*on_sys_linkat_returned_t)(CPUState* env,target_ulong pc,int32_t olddfd,target_ulong oldname,int32_t newdfd,target_ulong newname,int32_t flags);
typedef void (*on_sys_stat64_t)(CPUState* env,target_ulong pc,target_ulong filename,target_ulong statbuf);
typedef void (*on_rt_sigaction_t)(CPUState* env,target_ulong pc,int32_t sig,target_ulong act,target_ulong oact,uint32_t sigsetsize);
typedef void (*on_sys_fsync_t)(CPUState* env,target_ulong pc,uint32_t fd);
typedef void (*on_sys_setuid_t)(CPUState* env,target_ulong pc,uint32_t uid);
typedef void (*on_sys_statfs64_returned_t)(CPUState* env,target_ulong pc,target_ulong path,uint32_t sz,target_ulong buf);
typedef void (*on_sys_init_module_t)(CPUState* env,target_ulong pc,target_ulong umod,uint32_t len,target_ulong uargs);
typedef void (*on_sys_truncate64_returned_t)(CPUState* env,target_ulong pc,target_ulong path,uint64_t length);
typedef void (*on_vfork_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_umount_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t flags);
typedef void (*on_sys_setresgid_t)(CPUState* env,target_ulong pc,uint32_t rgid,uint32_t egid,uint32_t sgid);
typedef void (*on_sys_vhangup_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_ioprio_set_t)(CPUState* env,target_ulong pc,int32_t which,int32_t who,int32_t ioprio);
typedef void (*on_sys_pciconfig_write_returned_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_set_mempolicy_returned_t)(CPUState* env,target_ulong pc,int32_t mode,target_ulong nmask,uint32_t maxnode);
typedef void (*on_sys_newfstat_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong statbuf);
typedef void (*on_sys_wait4_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong stat_addr,int32_t options,target_ulong ru);
typedef void (*on_sys_creat_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_fork_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getresuid_t)(CPUState* env,target_ulong pc,target_ulong ruid,target_ulong euid,target_ulong suid);
typedef void (*on_sys_shutdown_t)(CPUState* env,target_ulong pc,int32_t arg0,int32_t arg1);
typedef void (*on_sys_mkdir_returned_t)(CPUState* env,target_ulong pc,target_ulong pathname,int32_t mode);
typedef void (*on_sys_rmdir_returned_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_link_returned_t)(CPUState* env,target_ulong pc,target_ulong oldname,target_ulong newname);
typedef void (*on_sys_chdir_t)(CPUState* env,target_ulong pc,target_ulong filename);
typedef void (*on_sys_sched_rr_get_interval_returned_t)(CPUState* env,target_ulong pc,uint32_t pid,target_ulong interval);
typedef void (*on_sys_getpgid_t)(CPUState* env,target_ulong pc,uint32_t pid);
typedef void (*on_sys_futimesat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,target_ulong utimes);
typedef void (*on_sys_fchown16_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t user,uint32_t group);
typedef void (*on_sys_pipe2_t)(CPUState* env,target_ulong pc,target_ulong arg0,int32_t arg1);
typedef void (*on_sys_sendfile_returned_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_get_mempolicy_t)(CPUState* env,target_ulong pc,target_ulong policy,target_ulong nmask,uint32_t maxnode,uint32_t addr,uint32_t flags);
typedef void (*on_sys_sendfile64_t)(CPUState* env,target_ulong pc,int32_t out_fd,int32_t in_fd,target_ulong offset,uint32_t count);
typedef void (*on_sys_unlink_t)(CPUState* env,target_ulong pc,target_ulong pathname);
typedef void (*on_sys_setgid_t)(CPUState* env,target_ulong pc,uint32_t gid);
typedef void (*on_sys_setdomainname_returned_t)(CPUState* env,target_ulong pc,target_ulong name,int32_t len);
typedef void (*on_sys_setgroups_returned_t)(CPUState* env,target_ulong pc,int32_t gidsetsize,target_ulong grouplist);
typedef void (*on_sys_epoll_ctl_t)(CPUState* env,target_ulong pc,int32_t epfd,int32_t op,int32_t fd,target_ulong event);
typedef void (*on_sys_writev_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong vec,uint32_t vlen);
typedef void (*on_sys_setpgid_t)(CPUState* env,target_ulong pc,uint32_t pid,uint32_t pgid);
typedef void (*on_sys_waitid_t)(CPUState* env,target_ulong pc,int32_t which,uint32_t pid,target_ulong infop,int32_t options,target_ulong ru);
typedef void (*on_sys_removexattr_returned_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong name);
typedef void (*on_sys_read_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,target_ulong buf,uint32_t count);
typedef void (*on_sys_epoll_wait_t)(CPUState* env,target_ulong pc,int32_t epfd,target_ulong events,int32_t maxevents,int32_t timeout);
typedef void (*on_sys_truncate64_t)(CPUState* env,target_ulong pc,target_ulong path,uint64_t length);
typedef void (*on_sys_capget_t)(CPUState* env,target_ulong pc,target_ulong header,target_ulong dataptr);
typedef void (*on_sys_pciconfig_read_returned_t)(CPUState* env,target_ulong pc,uint32_t bus,uint32_t dfn,uint32_t off,uint32_t len,target_ulong buf);
typedef void (*on_sys_inotify_rm_watch_returned_t)(CPUState* env,target_ulong pc,int32_t fd,int32_t wd);
typedef void (*on_sys_kill_returned_t)(CPUState* env,target_ulong pc,int32_t pid,int32_t sig);
typedef void (*on_sys_getuid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_mknodat_t)(CPUState* env,target_ulong pc,int32_t dfd,target_ulong filename,int32_t mode,uint32_t dev);
typedef void (*on_sys_ustat_t)(CPUState* env,target_ulong pc,uint32_t dev,target_ulong ubuf);
typedef void (*on_sys_mq_notify_returned_t)(CPUState* env,target_ulong pc,uint32_t mqdes,target_ulong notification);
typedef void (*on_ARM_user26_mode_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_llseek_returned_t)(CPUState* env,target_ulong pc,uint32_t fd,uint32_t offset_high,uint32_t offset_low,target_ulong result,uint32_t origin);
typedef void (*on_sys_umask_returned_t)(CPUState* env,target_ulong pc,int32_t mask);
typedef void (*on_sys_clock_getres_t)(CPUState* env,target_ulong pc,uint32_t which_clock,target_ulong tp);
typedef void (*on_sys_getpgrp_t)(CPUState* env,target_ulong pc);
typedef void (*on_do_mmap2_returned_t)(CPUState* env,target_ulong pc,uint32_t addr,uint32_t len,uint32_t prot,uint32_t flags,uint32_t fd,uint32_t pgoff);
typedef void (*on_sys_shmget_t)(CPUState* env,target_ulong pc,uint32_t key,uint32_t size,int32_t flag);
typedef void (*on_sys_readlink_t)(CPUState* env,target_ulong pc,target_ulong path,target_ulong buf,int32_t bufsiz);
typedef void (*on_sys_getppid_returned_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_getgid_t)(CPUState* env,target_ulong pc);
typedef void (*on_sys_keyctl_t)(CPUState* env,target_ulong pc,int32_t cmd,uint32_t arg2,uint32_t arg3,uint32_t arg4,uint32_t arg5);
typedef void (*on_sys_epoll_wait_returned_t)(CPUState* env,target_ulong pc,int32_t epfd,target_ulong events,int32_t maxevents,int32_t timeout);
#endif
