[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = [
    "pandare",
    "pandare.*"
]

[tool.setuptools.package-data]
pandare = [
    "data/*-softmmu/llvm-helpers*.bc*",  # LLVM Helpers
    "data/pypanda/include/*.h",  # Includes files
    "qcows.json"  # Generic Images
]

# This is how to setup cmd replacement, we can figure this out later
# [tool.setuptools.cmdclass]
# install = "setup.custom_install"
# develop = "setup.custom_develop"

[project]
name = "pandare"
dynamic = ["version"]
description = "Python Interface to PANDA"
readme = "README.md"
license = "GPL-2.0-or-later"
authors = [
    { name = "Luke Craig", email = "luke.craig@mit.edu" },
    { name = "Tim Leek" }
]
requires-python = ">=3.10, <3.14"
keywords = [
    "panda", 
    "pypanda", 
    "dynamic-analysis", 
    "reverse-engineering", 
    "whole-system-emulation", 
    "qemu", 
    "taint-analysis", 
    "record-replay", 
    "malware-analysis", 
    "binary-analysis", 
    "introspection", 
    "vmi", 
    "security-research"
]
dependencies = [
    "cffi>=1.14.3",
    "protobuf>=4.25.1",
    "colorama"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    
    # Intended Audience
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",

    # Topics & Domains
    "Topic :: Security",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Debuggers",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Emulators",
    
    # Supported Python Versions
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",

    # Operating System / Environment
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Natural Language :: English"
]
[tool.setuptools_scm]
root = "../../.."
fallback_version = "0.0.1"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project.scripts]
dwarfdump = "pandare.extras.dwarfdump:main"

[project.urls]
Homepage = "https://github.com/panda-re/panda"
Source = "https://github.com/panda-re/panda"
Tracker = "https://github.com/panda-re/panda/issues"
Documentation = "https://docs.panda.re/"
Download = "https://github.com/panda-re/panda/releases/latest"